### ISSUE TITLE
Experiencing Spontaneous Crashes [1.12.2]

### ISSUE THREAD

**Issue by Vulant** [CreativeMD/LittleFrames#11]
For the past few days I have been experiencing spontaneous crashes in which I rarely get a crash-report or anything useful in my latest.log or debug.log -- I would just crash to the launcher window with an exit code: 0. However, I have caught on to a few crash errors that may be responsible for what's happening. I updated CreativeCore and LT thinking that might fix the crashes I've been getting but, I'm still spontaneously crashing. I updated my graphics driver, made sure I had the latest java, restarted my computer, and the issue is still there. I've been consistently testing this theory all day and I only crash when LittleFrames has this gif playing somewhere in my world and I'm nearby. I doubt it's a RAM issue, I've got 32GB of RAM and allocated 7.5GB to MC.

Gif I've been playing on LittleFrames: https://imgur.com/zRKUVBS.mp4

Versions:
CreativeCore_v1.10.45_mc1.12.2.jar
LittleTiles_v1.5.0-pre324_mc1.12.2.jar
LittleFrames_v1.0.3_mc1.12.2.jar
MC 1.12.2 Forge 2854

Crash 1: https://pastebin.com/UdypB1Pf
Crash 2: https://pastebin.com/PKAQ7trt (My last crash so far, this time updated LT and CreativeCore, as well as removing VanillaFix from both client and server)
Crash 3: https://pastebin.com/VPe1QHC8 (As for this crash in particular, I don't know if it's due to LF / CreativeCore, but I get this one as often as I get Crash 2, so I feel like it might have something to do with it)

Steps to Reproduce:
1) Place frame down anywhere
2) Paste gif link into the frame
3) Stand somewhat close by to the frame and alt-tab out of the game
4) Do stuff on your computer
5) Spontaneous crash occurs, exit code: 0 with often times, no crash-report or any helpful errors in console logs or latest.log

**Comment by Vulant** [comment]
Two more additional crash reports from two others:

1) https://pastebin.com/R6SAgxPX
2) https://pastebin.com/fg8pmheA

**Comment by Vulant** [comment]
Been testing more on this, and I'm starting to think that these crashes are due to that specific gif. I feel like this may be the issue, since #8 exists. It also makes sense that it could be gif-specific issues, since I'm sure if it was entirely a mod issue that there would be way more reports similar to mine.

**Comment by CreativeMD** [comment]
I use VLC and VLCJ to implement it in java. I unfortunately can't help you with these errors, because they come from VLC directly and there is also nothing I can do to prevent them. Sorry ... maybe your VLC version is broken, I don't know. You could ask on the VLCJ github if they know how to fix it.
