### ISSUE TITLE
Only youtube videos are working, videos from other websites dont work

### ISSUE THREAD

**Issue by Juanescacha** [CreativeMD/LittleFrames#13]
Let me explain myself....
in VLC 3.0+ I can stream videos from many links from videos hosted on many websites.... (and following that logic, IT SHOULD work the same on the LittleFrame MOD in Minecraft right?)

But actually on the LittleFrame only works videos that are FROM youtube. Important to mention is that I dont have Whitelist enabled or something like that!

Specs:
minecraft 1.12.2 with forge
last littleframes mod version and all mods that are required
VLC 3.0+

I really want to solve this couse, i want to watch movies, or anime or another videos that are not allocated on youtube due to copyright, but watch it from another site like i dont know, facebook, mega, mediafire, vimeo, cuevana, animelflv or i dont know, you get my point right?

**Comment by CreativeMD** [comment]
Simple explanation. If it works in VLC it will work in LittleFrames. You can use "Media" -> "Open Network Stream" to test what works with VLC. Can't change anything about it, but a common mistake is to not link the actual file.

**Comment by Juanescacha** [comment]
@CreativeMD Thats what i mean, a link example (X) works on VLC in media->OpenNetworkStream BUT dont works in LittleFrames (in LittleFrames for me ONLY works Youtube Videos/Streamings).

As do I say, i have tested many links from many pages and in VLC in open network stream they all work, but no one works on littleframes, can you give me a link to test? or there is a way I or you can fix this issue for me? i dont know programming or api integration

**Comment by CreativeMD** [comment]
Maybe you are using a different VLC than LittleFrame detects? If you are using Java 64 bit (which you must likely will) LittleFrames will search for VLC 64 bit. Unfortunately the standard download is 32 bit.

**Comment by Juanescacha** [comment]
I will try that thing, but im sure i have vlc 64bits for windows, and the java i dont not
