### ISSUE TITLE
Crash while changing video selection

### ISSUE THREAD

**Issue by DoomRater** [CreativeMD/LittleFrames#15]
https://pastebin.com/az4tN6FE

The pastebin crash log refers to this video, but in embed form: https://www.youtube.com/watch?v=wthz3Rb3wnA

LittleFrames 1.0.7 is being used here, Creativecore 1.10.57, LittleTiles 1.5.6.  Will retry with CreativeCore 1.10.61 and LT 1.5.14 shortly.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Sorry that it took me so long.
