### ISSUE TITLE
Audio with distance (activating or not depending on the distance slider)

### ISSUE THREAD

**Issue by appollon41** [CreativeMD/LittleFrames#17]
Hello,

don't know if it is a bug or no, but the distance slider seems to change only the display and not the sound?
If it is actually not the case (and hoping it can be done before VLC 4.0), it would be nice introducing it (tryna make a cinema with multiple screens close that I'd want to separate via a precise distance).

Cheers, and big up for your work.

**Comment by CreativeMD** [comment]
Not possible, it's not supported. I hope it's better with VLC 4. The distance slider only works for rendering not for audio.
