### ISSUE TITLE
Crashing when going away or towards a LittleFrame

### ISSUE THREAD

**Issue by Vulant** [CreativeMD/LittleFrames#18]
**Crash Report:** 
https://haste.zneix.eu/yqerijimip.yaml

**Reproducibility:** 

I have a LF placed down with a video from youtube on. When I leave the area and am out of render distance of the frame, I crash. Likewise, if I am not in the area where the LF is and go towards it, upon reaching render distance, I will also crash. Maybe it has something to do with the video being paused while a player exits and re-enters the render distance? I truly do not know.
Myself and others are consistently crashing this way. We have all updated VLC player thinking that is what's going on, but we are still experiencing this issue.

I remember making another ticket #11 that is similar to this issue, but this time it is no longer spontaneous or random. It is consistently on the dot crashing. You told me in that ticket that there is nothing you can do there, but I hope maybe in this case you can ): I really, really, really want to use this mod and all it's potential!

If it helps, I did find another github post about a similar error with vlc player's dev linked here: https://github.com/caprica/vlcj/issues/1062 

**Versions:**
CreativeCore_v1.10.61_mc1.12.2.jar
LittleTiles_v1.5.17_mc1.12.2.jar
LittleFrames_v1.0.8_mc1.12.2.jar

**Comment by CreativeMD** [comment]
I'm very sorry, but I don't think I can fix it. This integration has a lot of problems and most of them I can't solve. I hope things get better when using VLC 4.0. Will close this issue, I recommend to avoid this feature :(
