### ISSUE TITLE
Support for using youtube-dl

### ISSUE THREAD

**Issue by DannyParker0001** [CreativeMD/LittleFrames#19]
youtube-dl is *much* better at fetching video streams for various sites from my experience. An example bash script of how to use youtube-dl with VLC can be found in [this issue](https://github.com/ytdl-org/youtube-dl/issues/2124#issuecomment-656319529).  
Could also be used to, for example, only play audio from sites that support it, such as vlc using --extract-audio 
Oh, and it could also (maybe, with some work) be used to play playlists.

**Comment by CreativeMD** [comment]
I will use VLC 4 in the next version, which will hopefully fix most of the issues.
