### ISSUE TITLE
Crash when clearing the URL from a playing YouTube video

### ISSUE THREAD

**Issue by DoomRater** [CreativeMD/LittleFrames#2]
https://pastebin.com/fgqUiMKF

This one is with LittleFrames pre4.  Was about to confirm Livestreams on Twitch when I caused this one.

**Comment by DoomRater** [comment]
Similar crash when clearing the URL from a Twitch.tv link. I attempted to stop it as well using the stop button first.

**Comment by CreativeMD** [comment]
One issue is fixed another one appears nice. I will take a look at it later.

**Comment by CreativeMD** [comment]
It's finally uploaded to curseforge, hope it will be approved soon. This issue should be fixed ... if it occurs nonetheless again just let me know.
