### ISSUE TITLE
Crash when rendering a littleframe

### ISSUE THREAD

**Issue by HeberonYT** [CreativeMD/LittleFrames#21]
Hello, I have 3 littleframes placed in my world, they are all playing a local video.
The problem happens when I am near them, suddenly the game freezes and eventually crashes.
Attached error report.

https://pastebin.com/raw/9fneugnD

LittleFrames_v1.0.8_mc1.12.2.jar
LittleTiles_v1.5.28_mc1.12.2.jar

**Comment by CreativeMD** [comment]
Seems like there is something wrong with your VLC player. Sorry but I cannot fix it. Maybe try to run the VLC player outside of minecraft and see if it actually works. Unfortunately this integration is very buggy and comes with many issues especially in Linux and MacOS.
