### ISSUE TITLE
Frame Placed, Now its indestructible, even in gamemode 1...

### ISSUE THREAD

**Issue by Blaze77gunYT** [CreativeMD/LittleFrames#24]
I can't get rid of it

**Comment by CreativeMD** [comment]
Does it crash? Is it the creative frame or a little frame?

**Comment by CreativeMD** [comment]
I will close this issue for now. I need more information in order to help out.

**Comment by Blaze77gunYT** [comment]
It’s a creative frame

**Comment by CreativeMD** [comment]
Is there a crash? Or why can't you remove it? You can also use the /setblock command

**Comment by Blaze77gunYT** [comment]
There isn’t any form of crash, I don’t know why I cannot remove it, /setblock commands or any other similar I’ve tried don’t work.
I managed to get rid of the “indestructible frame” by removing the mod and reinstalling it after doing a “clean save”.

**Comment by CreativeMD** [comment]
Can you see the frame or at least the outline?

**Comment by Blaze77gunYT** [comment]
I see a 1:1 “wooden plank”

**Comment by Blaze77gunYT** [comment]
The frame without any picture

**Comment by CreativeMD** [comment]
Is it inside spawn protection maybe?

**Comment by Blaze77gunYT** [comment]
Nope

**Comment by Blaze77gunYT** [comment]
Idk why it happened but it’s fixed now so don’t worry

**Comment by nycki93** [comment]
happened to me too. I posted an image from imgur that failed to load and now I can't break the frame.

**Comment by nycki93** [comment]
I ended up uninstalling and reinstalling the mod to get rid of it, since it was the only frame I'd placed so far.

**Comment by CreativeMD** [comment]
What version minecraft version are you using and can you send me your log file (of the session where you tried to remove it).

**Comment by nycki93** [comment]
Happened to me on 1.12.2, i will look and if it happens again i will share the log, sorry about that

**Comment by nycki93** [comment]
it just happened again, here is my log: https://mclo.gs/v3NYkbP

right before this, I clicked the X->Y button but it set the dimension to "NaN" and I accidentally clicked save instead of exiting. so maybe that's what causes it.

**Comment by nycki93** [comment]
as a workaround, I used creative mode to "setblock air" at the location of the bugged frame.

**Comment by CreativeMD** [comment]
Hey, sorry for not responding earlier. I do not support 1.12.2 anymore. Set to air seems to be a good choice.
