### ISSUE TITLE
Incompatibility with Normal Map=On in Optifine

### ISSUE THREAD

**Issue by Skyscoot9000** [CreativeMD/LittleFrames#25]
Turning on Normal Map results in 3/4 of an image being dark, pitch dark, or invisible (tested with Chocapic, SEUS(Renewed/PTGI), Continuum. If shader includes normal map autogen function and is turned on, the issue is fixed. If you require images please contact qwe9000#9324 in the Team Creative discord.

**Comment by CreativeMD** [comment]
I will add it to my todo list, so I can fix it for 1.18. I have dropped support for 1.12 a while ago. So sorry, but I won't fix it. Thanks for letting me know anyway! Very much appreciated. I could never figure out why it was doing that in the first place.
