### ISSUE TITLE
How i can change the size?

### ISSUE THREAD

**Issue by Hababarrio** [CreativeMD/LittleFrames#26]
Hi there!

I don´t know how to use the buttom crop/ strech someone can help me please?

It´s no so easy as the old one i just want to change the size :(

**Comment by CreativeMD** [comment]
Either you use the creativeframe which allows you to use any size or you use the littleframe. You can change the size when crafting it. Use the structurebuilder there you can define the dimensions.

**Comment by Hababarrio** [comment]
Thank you so much!! Totally in love with this mod! it´s an amazing work!

it´s there any guide to it?

**Comment by CreativeMD** [comment]
Not really, sorry :|

**Comment by Hababarrio** [comment]
We´ll manage step by step! Thank you so much again!!
