### ISSUE TITLE
Checking in if this is getting ported up?

### ISSUE THREAD

**Issue by VirtualGaming1** [CreativeMD/LittleFrames#27]
Hay I am just woundering that you are porting this. I just look around and saw an issue on online picture frame that you will be porting this but notice that you have not.

https://github.com/CreativeMD/OnlinePictureFrame/issues/69

Main thing is I am looking for like this in my modpack (Beta testing 1.18.2 currently) and I am going to have an arena on my official server and would be nice to see this working during an event.

**Comment by CreativeMD** [comment]
This mod will be ported once LittleTiles has been released for 1.19.
