### ISSUE TITLE
The brightness of little frames when using shaders is weird.

### ISSUE THREAD

**Issue by EagleZhen** [CreativeMD/LittleFrames#28]
I am using the Complementary Shaders v4.2.2 and somehow when using the shader, the little frame shows different brightness when looking from different angles/distances

Below are some of the examples when using different shaders.

[Example #1](https://cdn.discordapp.com/attachments/276752435869908993/1000674931132084284/2022-07-24_16-03-40.mp4)
[Example #2](https://cdn.discordapp.com/attachments/276752435869908993/1000677454236635146/2022-07-24_16-14-21.mp4)

**Comment by PenguinChoi5** [comment]
@EagleZhen I'm having an issue with little frames and complementary shaders as well, but in my case the frames don't even show anything aside from a black screen. How did you get yours to work?

**Comment by CreativeMD** [comment]
Sorry, but I cannot change anything about that. Shaders do their own thing :|

**Comment by PenguinChoi5** [comment]
No problem, I actually figured out that it wasn’t the shader, but my
version of VLC that was causing the issues. Thanks for the help though, I
appreciate it.

Your mods are great btw, I use them all the time so it’s nice to see that
your team is still trying to help bug fix them.
