### ISSUE TITLE
Game crashes while rendering LittleFrames

### ISSUE THREAD

**Issue by Blulitron** [CreativeMD/LittleFrames#29]
Since a few days, the game crashes at the same spot because of LittleFrames. However, the exact image it tries to render varies every time. An example crash report is pasted here:
https://pastebin.com/vt6ydhuE

I've also attached latest.log:
[latest.log](https://github.com/CreativeMD/LittleFrames/files/9332060/latest.log)

This might be a VLC sided issue, but I can't figure it out. VLC itself is up to date.

**Comment by CreativeMD** [comment]
This is a known issue and cannot be fixed unfortunately. I recommend to disable the VLC feature in config as it is quite buggy. I hope once VLC 4 comes out I can update and it will be more stable. For now there is nothing I can do about it, sorry :|

**Comment by Blulitron** [comment]
Deactivating VLC prevents the server from crashing, however the problematic images appear completely blank now. It seems only a few images I uploaded in a certain time span to Imgur are affected. Images I uploaded before or after that time span are fine. Very weird bug...
I think i might reupload the images and use different URLs, maybe this will fix it.
Thank you for the info!
