### ISSUE TITLE
Crash when destroying frame while it's playing video

### ISSUE THREAD

**Issue by em411** [CreativeMD/LittleFrames#3]
LF: LittleFrames_v1.0.2_mc1.12.2
LT: LittleTiles_v1.5.0-pre304_mc1.12.2
CC: CreativeCore_v1.10.40_mc1.12.2

As I mentioned in the title, game crashes when I'm breaking frame with working video player

> [14:41:04] [Client thread/INFO]: [com.creativemd.creativecore.transformer.CreativeTransformer:transform:49]: [littletiles] Patched net.optifine.DynamicLight ...
> [14:41:19] [Client thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
> 	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
> 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> Caused by: java.lang.NullPointerException
> 	at team.creative.littleframes.common.packet.LittleFramePacket.executeClient(LittleFramePacket.java:50) ~[LittleFramePacket.class:?]
> 	at com.creativemd.creativecore.common.packet.PacketReciever$1.run(PacketReciever.java:86) ~[PacketReciever$1.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
> 	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
> 	... 9 more
> [14:42:35] [Client thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
> 	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
> 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> Caused by: java.lang.NullPointerException
> 	at team.creative.littleframes.common.packet.LittleFramePacket.executeClient(LittleFramePacket.java:50) ~[LittleFramePacket.class:?]
> 	at com.creativemd.creativecore.common.packet.PacketReciever$1.run(PacketReciever.java:86) ~[PacketReciever$1.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
> 	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
> 	... 9 more
>

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
