### ISSUE TITLE
Doesn't work in forge 1.19.2 server

### ISSUE THREAD

**Issue by CelsiusIV** [CreativeMD/LittleFrames#30]
Hi,

I have test this mod in forge 1.19.2 (43.0.8) and work correctly in a **local world**. I also have a server with the same version but when I clicked in the frame the interface doesn't appear.  I tried with a oldest version of forge but doesn't work either.

This is what I use:
forge: 1.19.2 43.0.8
creative core: 2.8.2 (oldest version doesnt work in server with little frames mod)

Thank you so much

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue! You also have to update CreativeCore.

**Comment by CelsiusIV** [comment]
Thank you so much :)

**Comment by CreativeMD** [comment]
No problem, new version should hopefully be available in a few minutes.
