### ISSUE TITLE
Black picturein forge 43.1.1 (stable for 1.19.2)

### ISSUE THREAD

**Issue by CelsiusIV** [CreativeMD/LittleFrames#31]
I tried this mod in the stable version of forge and I only can see black pictures. If I change to previus version the picture looks correctly.
![2022-08-23_22 14 13](https://user-images.githubusercontent.com/48514985/186256920-c707a8c9-0881-4e35-992f-019c2d72ddef.png)

**Comment by CreativeMD** [comment]
Have you pressed play?

**Comment by CelsiusIV** [comment]
yes, although, it's a picture, not a video. And if i change the version and enter in the same world I can see it. (without pressing the play button)

**Comment by CelsiusIV** [comment]
more information: i tested in local and server, fails in both. Also I tried to put the frame in diferents blocks, change the size, change the picture...but it always black.

**Comment by CelsiusIV** [comment]
ok, it fails because optifine... I disabled optifine and now is working, could this be fixed? as i cant use rubidium i want to use optifine for the shaders, and the last version of optifine only works with the last stable version of forge.

**Comment by CreativeMD** [comment]
I can't do anything about the issue with Optifine. I'm currently trying to get the issue with rubidium solved.

**Comment by CreativeMD** [comment]
Update CreativeCore (new version should be available soon) and use rubidium instead. Crash should be fixed now.
