### ISSUE TITLE
Mod for 1.12.2 doesn't work

### ISSUE THREAD

**Issue by FulEnderboy** [CreativeMD/LittleFrames#32]
1.12.2 Jar doesn't work.
![image](https://user-images.githubusercontent.com/51930508/186282126-37fff28c-40ce-4dab-a390-94656963983a.png)

**Comment by CreativeMD** [comment]
You cannot launch the jar. You have to install it like every other mod by dragging it into the mods folder. I suggest to watch a tutorial about how to install forge mods.
