### ISSUE TITLE
This MOD works in Minecraft Java for Mac?

### ISSUE THREAD

**Issue by mv-nol** [CreativeMD/LittleFrames#33]
I performed several tests and could not make the video work in Minecraft Java on Mac M1. I tested with Intel and M1 versions from VLC app installed. Running Minecraft on M1 (Arm 64 Java runtime) the grame crash. Running as Intel, it works, but I always see a whiteboard with the VLC logo telling me to install VLC 3+ 64-bit. I performed tests with Youtube urls and also with local videos. Images are working great, but the videos never load! Thank you for your attention and congratulations for your work on this MOD.

**Comment by CreativeMD** [comment]
You have installed VLC 4?

**Comment by mv-nol** [comment]
I have tested with VLC 3.0.17 Arm-64 and Intel. Now I updated to VLC 4 Intel and it works great! Only do not work running Minecraft 1.9.2 in native M1 (the game crash). Running as Intel it is ok. Thank you for your fast reply.

**Comment by CreativeMD** [comment]
Sounds great! Glad it works now.
