### ISSUE TITLE
i've translated it into Chinese

### ISSUE THREAD

**Issue by CyberKanjousen** [CreativeMD/LittleFrames#34]
i've translated it into Chinese.
`
{
    "block.littleframes.creative_pic_frame": "Creative Picture Frame",
    "label.littleframes.not_whitelisted": "URL不在白名单, 无法保存!",
    "label.littleframes.whitelist_warning": "警告: URL白名单未启用",
    "gui.creative_frame.flipx": "翻转 (x轴)",
    "gui.creative_frame.flipy": "翻转 (y轴)",
    "gui.creative_frame.posx.left": "左移 (x)",
    "gui.creative_frame.posx.center": "居中 (x)",
    "gui.creative_frame.posx.right": "右移 (x)",
    "gui.creative_frame.posy.top": "置顶 (y)",
    "gui.creative_frame.posy.center": "居中 (y)",
    "gui.creative_frame.posy.bottom": "置底 (y)",
    "gui.creative_frame.visibleFrame": "相框可见",
    "gui.creative_frame.bothSides": "两边",
    "gui.creative_frame.rotation": "旋转",
    "gui.creative_frame.transparency": "透明度",
    "gui.creative_frame.brightness": "亮度",
    "gui.creative_frame.distance": "间距",
    "gui.creative_frame.volume": "体积",
    "gui.creative_frame.range": "范围",
    "gui.creative_frame.loop": "循环",
    "gui.creative_frame.reloadtooltip": "按住Shift键以重新加载全部",
    "gui.creative_frame.reload": "重新加载",
    "gui.creative_frame.save": "保存",
    "gui.frame_builder.width": "宽度:",
    "gui.frame_builder.height": "高度:",
    "gui.frame_builder.thickness": "厚度:",
    "gui.frame_builder.craft": "技巧",
    "gui.frame_builder.failed": "丢失的配方",
    "gui.little_frame.fitmode.CROP": "裁剪",
    "gui.little_frame.fitmode.STRETCH": "拉伸",
    "download.exception.forbidden": "禁用",
    "download.exception.notfound": "没有找到",
    "download.exception.invalid": "无法下载图像",
    "download.exception.gif": "加载GIF动画失败",
    "config.littleframes.sizeLimitation.commment": "最大框架大小(米)",
    "config.littleframes.maxRenderDistance.comment": "最大渲染距离(米)",
    "config.littleframes.onlyOps.comment": "是否只有op(管理员)可以编辑画框",
    "config.littleframes.disableAdventure.comment": "如果是, 则玩家在冒险模式将无法编辑画框",
    "config.littleframes.onlyCreative.comment": "如果是, 则只有在创造模式可以编辑画框",
    "config.littleframes.whitelistEnabled.comment": "如果是, 则只有白名单中列出的url可用于画框",
    "config.littleframes.whitelist.comment": "可用在画框里的url列表"
}
`
please copy it into "zh_cn.json", OK?

**Comment by qznfbnj** [comment]
Maybe you can open a new pull request? Its format should follow en_zh.json.
你可以开个新的 PR 啊，记得格式要遵从 en_zh.json 的。
