### ISSUE TITLE
picture or video glitches up when I move by head

### ISSUE THREAD

**Issue by Smirkish** [CreativeMD/LittleFrames#36]
idk why whenever I try to add a picture or a video, it would start glitching up by disappearing unless I look at it, is there a way to fix this?

https://user-images.githubusercontent.com/113142364/189661850-f4a2a7d7-9e21-45c3-b19d-9e8e165637ae.mp4

**Comment by CreativeMD** [comment]
Which version of the mod are you using? Are you on 1.12 or 1.19?

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity.
