### ISSUE TITLE
Crash while trying to place 2nd littleframe 

### ISSUE THREAD

**Issue by Crossik99** [CreativeMD/LittleFrames#37]
While I try to use littleframe, to add 2nd one near the first, even if it's blank, my game just stop rendering, I can see just a sky, then it crashes. Game version 1.12.2. Modpack: https://imgur.com/a/sFBD5X4

**Comment by CreativeMD** [comment]
I need the crash-report. You can find it in the minecraft folder. There is a subdirectory called crash-reports.

**Comment by CreativeMD** [comment]
I will close this issue for now. I need more information. You can still respond here and I will reopen the issue once you reply.
