### ISSUE TITLE
Fabric?

### ISSUE THREAD

**Issue by pocinhas** [CreativeMD/LittleFrames#38]
Hey there. I hope I'm not being one of those spammy obnixious commenters asking for it, but are you considering porting the mod to fabric? I didn't see anyone else asking for it so I went ahead and gave it a shot :)

**Comment by CreativeMD** [comment]
No this mod will not be ported to Fabric, unless somebody else decides to do it. I'm happy to maintain it, but I do not have the time to port all of this stuff over to fabric.
