### ISSUE TITLE
1.12.2 Crash

### ISSUE THREAD

**Issue by voidswrath** [CreativeMD/LittleFrames#39]
Crash on loadup for client. 

forge: 2860
VLC 3 
CreativeCore_v1.10.70_mc1.12.2.jar

https://paste.ee/p/SvwbE

**Comment by voidswrath** [comment]
required little tiles. For some reason that is not listed as a dependency

**Comment by CreativeMD** [comment]
I have checked it and it requires LIttleTiles on curseforge. Make sure you installed it as well and your issue should be fixed.
