### ISSUE TITLE
Option to have audio decrease in volume based on distance.

### ISSUE THREAD

**Issue by Zundrel** [CreativeMD/LittleFrames#4]
I'd like an option to have the audio decrease when moving away from the frame (when playing videos and such). The way it works now makes it hard to use them on a server since the audio is broadcast so far away at full volume.

It'd be especially nice if this option was configurable per frame, so you could set the range of audio on the frame. This would work great for stuff such as TVs or even movie theaters. Preferably this would also be separated from the visual range.

**Comment by CreativeMD** [comment]
Unfortunately that is not possible. At the moment there is only one audio control for all videos. Means that all videos will have the same volume, if that changes over distance it would affect all other videos in the same way. This will be fixed once VLC 4.0 is released, but I'm not sure when this will happen.
