### ISSUE TITLE
1.19.2 Crashes on Joining Server/Region with Images

### ISSUE THREAD

**Issue by Wubzzz1337** [CreativeMD/LittleFrames#41]
Hi,

As titles says.

I have a Void World with a mob farm in it, I have some picture there with the "Animals" to know which lever activates what.
They are just PNGs.

Whenever I join the server/world it crashes (not always tho, it's random)

I have VLC Client-side Disabled, also uninstalled V4 just to check if it was that, but still crash.

Minecraft Version: 1.19.2
Forge: 43.1.57
Latest Version of your mod.

Modpack: https://www.curseforge.com/minecraft/modpacks/equal2you

The only error log I get is this:
[hs_err_pid5728.log](https://github.com/CreativeMD/LittleFrames/files/10457280/hs_err_pid5728.log)
[hs_err_pid18944.log](https://github.com/CreativeMD/LittleFrames/files/10457281/hs_err_pid18944.log)

**Comment by CreativeMD** [comment]
Can you send me the log file?

**Comment by Wubzzz1337** [comment]
[debug-2.log.gz](https://github.com/CreativeMD/LittleFrames/files/10458167/debug-2.log.gz)
[2023-01-19-3.log.gz](https://github.com/CreativeMD/LittleFrames/files/10458168/2023-01-19-3.log.gz)
[debug-3.log.gz](https://github.com/CreativeMD/LittleFrames/files/10458169/debug-3.log.gz)
[2023-01-19-2.log.gz](https://github.com/CreativeMD/LittleFrames/files/10458170/2023-01-19-2.log.gz)

I think those are the correct one, not sure tho. Sry

**Comment by CreativeMD** [comment]
This issue should not happen anymore. Does it work in singleplayer?

**Comment by Wubzzz1337** [comment]
Haven't tested it there, but since I only play via my Server.

**Comment by CreativeMD** [comment]
Can you still try to create a new world in singleplayer use the same url and see if it crashes?

**Comment by CreativeMD** [comment]
I will close this issue for now. If there are any news just post them here and I will reopen the issue.
