### ISSUE TITLE
downloaded videos only works

### ISSUE THREAD

**Issue by Smirkish** [CreativeMD/LittleFrames#42]
hello, so I'm writting this message to tell the owner of this mod that I'm facing a problem with the video url in little picture frames, well, whenever I insert a video url from youtube, the video doesn't work and it shows up a white screen, downloaded videos are only working, is there a way to fix this problem? thank you.

**Comment by CreativeMD** [comment]
That is unfortunately an issue of VLC itself. It does not work great with youtube. You can use urls which point directly to a video file. There is also a fix you can apply to your VLC installation to make youtube work (google: `vlc youtube.lua fix`), but even then it does not work great. I hope VLC will tackle this issue at some point.
