### ISSUE TITLE
[1.19.2] Frame tells me I need VLC installed, but it already is.

### ISSUE THREAD

**Issue by OopityDoop** [CreativeMD/LittleFrames#45]
@CreativeMD 
I have the latest VLC build, but when I try to put a video in the frame, it shows this.
![2023-02-15_20 27 25](https://user-images.githubusercontent.com/65684468/219239953-91547d43-4a82-4299-b17c-511c40decba4.png)
I am clicking copy video link on YT and copy video address everywhere else, but they both yield this.
Images and gifs work as intended.

**Comment by CreativeMD** [comment]
The version for 1.19.2 requires a VLC 4 release from September: https://artifacts.videolan.org/vlc/nightly-win64/20220909-0423/
Also make sure to install it into the default location. Furthermore you need the 64-bit version.

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists just write it here.
