### ISSUE TITLE
FPS drops when I add a picture

### ISSUE THREAD

**Issue by SmirkishBoi** [CreativeMD/LittleFrames#46]
hello, I'm using the latest version of LittleFrames 1.12.2, and I'm facing an issue which is whenever I add one picture or more, my fps starts dropping and it will then crash, is there a way to fix this issue?
thanks

**Comment by SmirkishBoi** [comment]
hello????

**Comment by CreativeMD** [comment]
Sorry for not responding earlier, I was on vacation. Can you send me the crash-report and the log file?

**Comment by SmirkishBoi** [comment]
I don't know where did it go, I think the crash happened a few weeks ago but then I have maybe lost its log file, but all I know is that whenever I add a picture, the fps starts dropping

**Comment by SmirkishBoi** [comment]
plus, I have a bunch of log files inside the log folder, which I think it will be hard to find the LittleFrames mod's log file

**Comment by SmirkishBoi** [comment]
Nevermind, I found them
here you go

**Comment by SmirkishBoi** [comment]
[2023-03-30-6.log](https://github.com/CreativeMD/LittleFrames/files/11191223/2023-03-30-6.log)
[2023-03-30-7.log](https://github.com/CreativeMD/LittleFrames/files/11191229/2023-03-30-7.log)
[2023-03-30-1.log](https://github.com/CreativeMD/LittleFrames/files/11191232/2023-03-30-1.log)

**Comment by SmirkishBoi** [comment]
Those are the log files of The LittleFrames mod

**Comment by CreativeMD** [comment]
Could not find anything in the logs. One of the logs shows a issues when loading images, but that should not be a problem. Can you explain your situation further? What are you trying to do? What happens when? Maybe you could do a short video (if that is possible) or a few screenshots with F3 enabled to show the issue.

**Comment by SmirkishBoi** [comment]
alright

**Comment by SmirkishBoi** [comment]
ok so, this is a map which it has my mansion built into it, and it has also a lot of LittleFrames pictures inside it, and as you can see, my fps are dropping, and if I add another picture or even more, the fps starts dropping. https://drive.google.com/file/d/16I2uRdhAylVCZLDi5LW8VnG50bVwQ_NN/view?usp=sharing

**Comment by CreativeMD** [comment]
I doubt there is something I can do about it. Normally the fps impact is minimal, but seems like your graphics card struggles a bit more with it. I thought it would be a mod compatibility issue, but that is definitely not the case. Sorry I cannot really help you there, that's just how it is. Features like these can impact fps. Also very sorry for my late response. Feel really bad that I cannot help you there.

**Comment by SmirkishBoi** [comment]
I see
