### ISSUE TITLE
Lagspikes when start to play a new video

### ISSUE THREAD

**Issue by SrRapero720** [CreativeMD/LittleFrames#47]
This is caused by VLC. trying to load media on the render thread
this can be fixed creating a new thread for this line

https://github.com/CreativeMD/LittleFrames/blob/300ac7f8eacdcb7f510a9c3aee02cee8205580ff/src/main/java/team/creative/littleframes/client/display/FrameVideoDisplay.java#L129

Someting like this
```java
var thread = new Thread(() -> player.mediaPlayer().media().start(url));
thread.setName("LF/Play");
thread.setDaemon(true);
thread.start();

```

**Comment by CreativeMD** [comment]
Thanks a lot for your suggestion. Sorry for not responding earlier. Added it in the newest version. Not sure if the lag spike will be gone now, we shall see.

**Comment by SrRapero720** [comment]
Only is required on play method
other methods only set vars but no start to process media. just to prevent more bugs

**Comment by CreativeMD** [comment]
I did not notice any difference in the lag spike to be honest. That's why I thought more would be better. At least on my system it did not change anything.

**Comment by SrRapero720** [comment]
Is pretty notable

BEFORE:
<video src="https://user-images.githubusercontent.com/29090346/235103831-0393e815-5d20-4a32-8976-2bcc0749cdf7.mp4"></video>

AFTER:
<video src="https://user-images.githubusercontent.com/29090346/235104911-071afe44-73a4-4807-b347-b68c308203fc.mp4"></video>

**Comment by CreativeMD** [comment]
Nice, maybe it's because I only played an audio file with vlc. Thanks again for your help! Very good job! (Will do the change, but wait to release once there is something else has changed as well).

EDIT:
Actually can you try out if there is a difference if all is threaded and just the start call? I will upload a new version. Would be cool if you could test it.

**Comment by CreativeMD** [comment]
https://www.dropbox.com/s/fmc92kda8xvreih/LittleFrames_FORGE_v1.1.16_mc1.19.4.jar?dl=1

This version only threads the start call. Maybe it's more laggy than threading everthing?

**Comment by SrRapero720** [comment]
i made that test in a backported version of LF. keeps the same performance
https://github.com/SrRapero720/WATERFrAMES

Btw the main reason of why i only suggest to thread the start call is by this:
Crash: https://gist.github.com/SrRapero720/998e317ebbfb9b752432c035f0553025
Build with the gist crash: https://www.curseforge.com/minecraft/mc-mods/littleframes/files/4508008

threading everything causes crashes with placed frames, rejoining a server or singleplayer world with video-frames and sometimes placing new frames in fresh worlds. And no reduces more lag (that threaded start call can do)
Using the 1.1.16 build haven't that crash

**Comment by CreativeMD** [comment]
Ok, thanks a lot for testing it out! Uploaded 1.1.16 to curseforge and modrinth. Cannot thank you enough for all your effort!
