### ISSUE TITLE
Incompatibilty problem

### ISSUE THREAD

**Issue by Notimagination** [CreativeMD/LittleFrames#48]
Hello, LittleFrames has an incompatibilty with [ChatImage](https://www.curseforge.com/minecraft/mc-mods/chatimage) mod
I'm using Minecraft 1.19.2, can you check it? Also, the 1.19.2 version of LittleFrames has no update for a long time

**Comment by CreativeMD** [comment]
Yes, it appears to be fixed in 1.19.4, but I will not fix it for 1.19.2, sorry.
