### ISSUE TITLE
Pictures no get rendered using shaders

### ISSUE THREAD

**Issue by SrRapero720** [CreativeMD/LittleFrames#49]
Right now. littleframes no show any picture on 1.19.4 using shaders. 
(take your time to read this, i documented everything): https://github.com/SrRapero720/waterframes/issues/1 <br>

# Screenshots
![2023-05-05_15h33_40](https://user-images.githubusercontent.com/29090346/236572649-5cef7cd8-40f8-430f-a9c2-f2038b961f71.png)
![2023-05-05_15h33_33](https://user-images.githubusercontent.com/29090346/236572655-ec790b45-7e24-4940-bed0-5eba63ea83b5.png)

---

I make a backport of littleframes 1.19.4 to 1.19.2 and that version CANT show pictures with shaders. but the current [1.19.2](https://www.curseforge.com/minecraft/mc-mods/littleframes/files/3996679) can do. At the first wave trying to solve this problem i solve it just changing ShaderInstance with `GameRenderer::getPositionTexColorShader` but shaders apply a weird shadown and tint the picture with a weird orange.

# Screenshot
![image](https://user-images.githubusercontent.com/29090346/236573728-7af59d6a-dfc2-4d60-a21b-d2bd112ebb5c.png)
---

I spend a lot of time trying to figure out what is wrong in waterframes, reading littleframes code 10 times figure out what is wrong. if i remove/skip someting but problem is from both mods. Turning off realistic clouds fix the issue, but brightness on pictures get ignored and isn't a good workaround.

# Screenshots
How works LittleFrames 1.19.2
![image](https://user-images.githubusercontent.com/29090346/236573863-183c03ae-253e-4ef4-8730-949caf67d3d1.png)
How works LittleFrames/Waterframes in 1.19.4 using BSL without realistic clouds
![2023-05-05_15h45_09](https://user-images.githubusercontent.com/29090346/236573868-230a4ee4-6a19-4853-8c8a-aced16f9e32c.png)

# Posibles fix
Revert https://github.com/CreativeMD/LittleFrames/commit/e6f87fbbc8dd2dd1c05dc709123f278f8e4d65ce
Is the best solution right now. if people see frames very bright they can reduce it in frame config or change shader config to reduce shader brightness (Example with BSL)

![2023-05-05_15h54_30](https://user-images.githubusercontent.com/29090346/236575273-16d5ad81-ef9b-4afd-a30c-5018432d4a94.png)

---
Use this fix: https://github.com/SrRapero720/waterframes/commit/d43178579eb6b0a575bdd827e389cc7f5f787192#diff-a315acec4ad95757cfe4ed0c13b71b2484578f5c4f635339fd9124e7f95358dcR84
The counterpart is pictures get a yellow tint with some shaders and weird shadows on picture borders

**Comment by CreativeMD** [comment]
First of all thanks a lot for all your effort. Very cool to see you taking the time to document it well.

Compatibility with shaders always has been quite a struggle. Shaders often struggled to calculate proper shadow, which often times resulted in the frame being dark while being in the sunlight. Somebody suggested to me that this has to do with the normals: https://github.com/CreativeMD/LittleFrames/issues/25. So I changed it to get rid of the issue.

I have started to test it on my own. I have tried out various things. To use a different format, added all kinds of render system calls, added my own shader format. Nothing works. Changing it back is probably the easiest solution, but I will try a few more things before I give up. I also contacted the author of the BSL Shader, he could not really help me. Currently trying to get in contact with the authors of Rubidium and Oculus. Let's see. BTW, using Optifine this issue does not occur, but it actually has the same result as leaving out the normals.

**Comment by SrRapero720** [comment]
I had forgotten to send updates regarding

I was testing with the old shader (getPositionTexShader) from littletiles 1.19.2 and it generates crashes with some shaders I've tried (Makeup ultra-fast) so the only quick solution is to use getPositionTexColorShader
Crashes for example: https://gist.github.com/SrRapero720/502d7c72aabac097604a9c2af45b0427

I was testing and with all shaderpacks i have doesn't crash and it works with or without shaders. the only detail is the overglow and the orange tint which can be fixed by adjusting the blocklight properties which include the shader settings
Details here: https://github.com/SrRapero720/waterframes/wiki/Incompatible-Shaders-(and-how-to-make-it-compatible)

with this the only shader that is incompatible with WF and LF would be ComplementaryV4 which overbright the image. but everything else is fine.
![2023-05-09_14h48_50](https://github.com/CreativeMD/LittleFrames/assets/29090346/94790b7c-f56e-4be9-ad5a-f3e94b99f6e3)

### The only issue is that weird deformed shadow in front of the image that i dont know what cause it. but is a minor inconvenient.
![2023-05-09_14h50_52](https://github.com/CreativeMD/LittleFrames/assets/29090346/4ea3b2d7-da6e-4a05-bf5f-f8242988c2cf)
![2023-05-09_14h50_34](https://github.com/CreativeMD/LittleFrames/assets/29090346/ae8149d2-e55c-4f21-95db-0bf877fe0289)

**Comment by CreativeMD** [comment]
I have applied your suggested fix for the moment. I could not find a different way to get rid of this issue. Maybe in 1.20 there will be a new way.
