### ISSUE TITLE
Game lags when loading large/long GIF images

### ISSUE THREAD

**Issue by Treeways** [CreativeMD/LittleFrames#50]
When a chunk is initially loaded, the game freezes when loading a large image with long playback. The image in question here is a 43.1MB GIF, and runs for several minutes (probably more than 5-10 minutes).

Reproduction steps:

1. Make a Creative Picture Frame with a large GIF image (large file size, very long playback time).
2. Move away about 500-800 blocks from the frame.
3. Move towards the frame to reload it, and witness a 2 second client-side lag spike on the way to the room.

Here's a Spark profile: https://spark.lucko.me/XmHdSabOPO

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. This is obviously quite a large give. I recommend to install VLC instead. Can you try if the newest version 1.2.0 still has this long lag spike?

**Comment by SrRapero720** [comment]
this has been addressed on watermedia 2.0.54
now the gif decoding is done offthread
