### ISSUE TITLE
[1.19.2] Mod not displaying videos

### ISSUE THREAD

**Issue by ghost** [CreativeMD/LittleFrames#52]
![image](https://github.com/CreativeMD/LittleFrames/assets/101234746/d83464ef-d57c-489f-9dfe-179fc3c66a38)

Hey, I've been trying to use LittleFrames in my modpack but this keeps happening. I'm able to post links to images from the internet into the frames and they show just fine, but when I try to use links for videos (like youtube) it shows me the message above. Can't the mod get videos from the internet, or is it some type of error that I need to fix? Thnx

Attempts to fix error:

- Reinstall VLC; my version: https://artifacts.videolan.org/vlc/nightly-win64/20230527-0427/ from 27-May-2023 (I tried downloading the September release as instructed on the CurseForge page but the link cannot be found anymore).

- youtube.lua fix; I'm able to post the link for the video into VLC and it plays on VLC, but when I try pasting it in-game it shows me the message above.

**Comment by CreativeMD** [comment]
LittleFrames does not detect VLC at all. This has nothing to do with the version. Make sure to install VLC in the default directory. Maybe try to use LittleFrames for 1.19.4 just to see if this version can detect your VLC.

**Comment by CreativeMD** [comment]
Switched back to VLC 3 thanks to @SrRapero720. Get the newest version install VLC 3 and it should work!
