### ISSUE TITLE
VLC bug creative picture frame.

### ISSUE THREAD

**Issue by ncsasp** [CreativeMD/LittleFrames#53]
Pasting a youtube link (or any other video file) into the creative picture frame results in the "download vlc" image rather than actual video, despite having downloaded vlc and all dependencies. Video file works (apart from buffering) in VLC itself, but not in game.
Using prism launcher on 1.19.2
![Capture](https://github.com/CreativeMD/LittleFrames/assets/58613316/dd15b7bb-0a03-4776-a290-cdef212b4248)
![Capture](https://github.com/CreativeMD/LittleFrames/assets/58613316/b98e5298-6967-4619-b400-44eb6be6438c)

**Comment by CreativeMD** [comment]
Sorry for responding that late. Issue is the required VLC 4 version is not available anymore. I plan to change a lot related to LittleFrames soon. I will upload a version for 1.19.2 to fix this issue as well.

**Comment by RedEyesSteveYT** [comment]
VLC IS NOT WORKING FOR ME TOO WHAT IS THIS BRO FIX THIS!!!!!!!!!!!!!!!!

**Comment by SrRapero720** [comment]
@RedEyesSteveYT Fix Is done, but you are banned to use It :3

**Comment by RedEyesSteveYT** [comment]
why
i want to use it man

**Comment by SrRapero720** [comment]
@RedEyesSteveYT because you are so RUDE kiddo. Please wait until fix is done. Dev Is bussy sometimes and do coding things takes time.

**Comment by RedEyesSteveYT** [comment]
ok sorry pls forgive me and unban me bro

**Comment by CreativeMD** [comment]
@RedEyesSteveYT how did you fix it?

**Comment by CreativeMD** [comment]
Switched back to VLC 3 thanks to @SrRapero720. Get the newest version install VLC 3 and it should work!
