### ISSUE TITLE
UrlTextField is limited to 128 chars but URLs are limited to 2048

### ISSUE THREAD

**Issue by SrRapero720** [CreativeMD/LittleFrames#54]
This causes a curious issue. paste a URL forces to UrlTextField to handle the entire URL. but when Gui is re-opened cuts the URL and breaks the picture (couln't load)

suggestion: increase char limit to 2048
put text and after changes limit doesn't works, set text on constructor cuts the URL before set new input limit
so is necesary to do the change on UrlTextField class

https://github.com/CreativeMD/LittleFrames/blob/75aee9d6f4429d27960f3581d6520ab358e60732/src/main/java/team/creative/littleframes/client/gui/GuiUrlTextfield.java#L19

removing argument "text" and adding another line with
```java
        setMaxStringLength(2048);
        setText(text);
```

**Comment by CreativeMD** [comment]
Thank you very much for all your help! Have not been aware of it.
