### ISSUE TITLE
1.16.5 version 

### ISSUE THREAD

**Issue by Breckeur** [CreativeMD/LittleFrames#56]
Hi im here to say that there is no 1.16.5 version only 1.12.2 or 1.19+ why ?
Because i have an custom modpack and i wanted to add that mod  for it. 
Thaks for reading and eventual reacts.

**Comment by CreativeMD** [comment]
Sorry, but there is no version for all the versions in between because I did not port the mod earlier. I will not add support for these versions now. Please consider upgrading to newer versions.
