### ISSUE TITLE
[1.20.1] Game crashes when attempting to break frame in survival

### ISSUE THREAD

**Issue by ghost-trip** [CreativeMD/LittleFrames#58]
I've used this mod for a while now and I've always loved it. I would say it's one of my favorite mods. However, ever since OnlinePictureFrame became LittlePictureFrames I've had plenty of crashes with this mod. I understand the frame can only be accessed through creative now, but I enjoy using it in my survival server. Left-clicking on the frame will cause me to crash, but otherwise works fine. This problem happens for me in both singeplayer and multiplayer. Sorry for the long crash report in advance..

[crash.txt](https://github.com/CreativeMD/LittleFrames/files/12063286/crash.txt)

**Comment by CreativeMD** [comment]
Fixed in the newest version v1.2.1. Thanks for reporting this issue!
