### ISSUE TITLE
Crash when destroying frame while it's playing video - still exists

### ISSUE THREAD

**Issue by em411** [CreativeMD/LittleFrames#6]
LF: LittleFrames_v1.0.3_mc1.12.2
LT: LittleTiles_v1.5.0-pre315_mc1.12.2
CC: CreativeCore_v1.10.44_mc1.12.2

Forge: forge-1.12.2-14.23.5.2855

> Description: Rendering Block Entity
> 
> 
> java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@3543250d rejected from java.util.concurrent.ThreadPoolExecutor@6dfc1014[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 29]
> 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
> 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
> 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
> 	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
> 	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
> 	at uk.co.caprica.vlcj.support.eventmanager.TaskExecutor.submit(TaskExecutor.java:68)
> 	at uk.co.caprica.vlcj.player.base.MediaPlayer.submit(MediaPlayer.java:264)
> 	at team.creative.littleframes.client.display.FrameVideoDisplay.release(FrameVideoDisplay.java:165)
> 	at team.creative.littleframes.common.structure.LittleFrame.renderTick(LittleFrame.java:178)
> 	at com.creativemd.littletiles.client.render.world.TileEntityTilesRenderer.render(TileEntityTilesRenderer.java:55)
> 	at com.creativemd.littletiles.client.render.world.TileEntityTilesRenderer.func_192841_a(TileEntityTilesRenderer.java:15)
> 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:201)
> 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:157)
> 	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1031)
> 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1808)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
> 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>

**Comment by CreativeMD** [comment]
It's not the same issue and I can't do anything about it unfortunately :(

**Comment by CreativeMD** [comment]
I have dropped support for 1.12.
