### ISSUE TITLE
Feature Request Redstone interaction

### ISSUE THREAD

**Issue by NateKDavis** [CreativeMD/LittleFrames#61]
I would love to be able to start and stop the frame with redstone. Would be great for music that way.

**Comment by CreativeMD** [comment]
Has been implemented in the newest version. You can control it via signals from LittleTiles.

**Comment by Gannio** [comment]
This feels like less of a proper solution and more overengineering? While it's helpful for those using LittleFrames to begin with, requiring users install a mod that adds a large amount of complexity for those that just want a simple experience with the added ability to start/stop media in response to redstone, without needing to rework their understanding of it.

A large application of this could be things like small voice clips, music, or other interactive elements when solely considering the audio portion, or instructional videos/theaters with regards to the video portion.

**Comment by CreativeMD** [comment]
@Gannio I get your point. Newest version can be pause and resume via redstone.

![Image](https://github.com/user-attachments/assets/d5127e74-5110-4d77-8a6c-cce1a179f14d)
