### ISSUE TITLE
Problem with dependencies and crash

### ISSUE THREAD

**Issue by SETHPROSYT** [CreativeMD/LittleFrames#62]
**When I want to open the game with little picture frames and creative core I get this error**

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MSICCoreMod (MyServerIsCompatible-1.12.2-1.0.jar)
  SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.8.jar)
  McLib core mod (mclib-2.4.2-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  FutureMC (future-mc-0.2.11.jar)
  Moving Elevators Plugin (movingelevators-1.4.4-forge-mc1.12.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_23.8.0_Forge_1.12.jar)
  LootrCore (lootr-1.12.2-0.6.2.jar)
  MixinBooter (!mixinbooter-8.6.jar)
  CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  SuperMartijn642's Core Lib Plugin (_supermartijn642corelib-1.1.15-forge-mc1.12.jar)
  infwithmend (infwithmend-forge-1.12.2-1.0.0.jar)
  Let Me Despawn (letmedespawn-1.12.2-forge-1.0.2.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.34.1_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 10/13/23 2:55 PM
Description: Initializing game

java.lang.NoClassDefFoundError: team/creative/littleframes/LittleFrames$1
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: team.creative.littleframes.LittleFrames$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 38 more
Caused by: java.lang.NoClassDefFoundError: com/creativemd/littletiles/client/gui/handler/LittleStructureGuiHandler
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more
Caused by: java.lang.ClassNotFoundException: com.creativemd.littletiles.client.gui.handler.LittleStructureGuiHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 44 more

(MixinBooter) Mixins in Stacktrace:
	net/minecraftforge/fml/common/LoadController:
		zone.rong.mixinbooter.mixin.LoadControllerMixin (mixin.mixinbooter.init.json) [unknown-location]
	net/minecraft/client/Minecraft:
		net.geforcemods.securitycraft.mixin.camera.MinecraftMixin (securitycraft.mixins.json) [unknown-location]
		de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json) [unknown-location]
	net/minecraftforge/fml/client/FMLClientHandler:
		com.focamacho.myserveriscompatible.mixin.MixinFMLClientHandler (mixins.myserveriscompatible.json) [unknown-location]
	net/minecraftforge/fml/common/LoadController:
		zone.rong.mixinbooter.mixin.LoadControllerMixin (mixin.mixinbooter.init.json) [unknown-location]
	net/minecraft/client/Minecraft:
		net.geforcemods.securitycraft.mixin.camera.MinecraftMixin (securitycraft.mixins.json) [unknown-location]
		de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json) [unknown-location]
	net/minecraftforge/fml/client/FMLClientHandler:
		com.focamacho.myserveriscompatible.mixin.MixinFMLClientHandler (mixins.myserveriscompatible.json) [unknown-location]
	net/minecraftforge/fml/common/LoadController:
		zone.rong.mixinbooter.mixin.LoadControllerMixin (mixin.mixinbooter.init.json) [unknown-location]
	net/minecraft/client/Minecraft:
		net.geforcemods.securitycraft.mixin.camera.MinecraftMixin (securitycraft.mixins.json) [unknown-location]
		de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json) [unknown-location]
	net/minecraftforge/fml/client/FMLClientHandler:
		com.focamacho.myserveriscompatible.mixin.MixinFMLClientHandler (mixins.myserveriscompatible.json) [unknown-location]
	net/minecraftforge/fml/common/LoadController:
		zone.rong.mixinbooter.mixin.LoadControllerMixin (mixin.mixinbooter.init.json) [unknown-location]
	net/minecraft/client/Minecraft:
		net.geforcemods.securitycraft.mixin.camera.MinecraftMixin (securitycraft.mixins.json) [unknown-location]
		de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json) [unknown-location]
	net/minecraftforge/fml/client/FMLClientHandler:
		com.focamacho.myserveriscompatible.mixin.MixinFMLClientHandler (mixins.myserveriscompatible.json) [unknown-location]

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_381, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 106393840 bytes (101 MB) / 469762048 bytes (448 MB) up to 3758096384 bytes (3584 MB)
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx3584m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 101 mods loaded, 100 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                 | Source                                                 | Signature                                |
	|:----- |:------------------------ |:----------------------- |:------------------------------------------------------ |:---------------------------------------- |
	| LC    | minecraft                | 1.12.2                  | minecraft.jar                                          | None                                     |
	| LC    | mcp                      | 9.42                    | minecraft.jar                                          | None                                     |
	| LC    | FML                      | 8.0.99.99               | forge-1.12.2-14.23.5.2860.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                    | 14.23.5.2860            | forge-1.12.2-14.23.5.2860.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy        | 1.0.0                   | minecraft.jar                                          | None                                     |
	| LC    | xaerominimap_core        | 1.12.2-1.0              | minecraft.jar                                          | None                                     |
	| LC    | xaeroworldmap_core       | 1.12.2-1.0              | minecraft.jar                                          | None                                     |
	| LC    | mixinbooter              | 8.6                     | minecraft.jar                                          | None                                     |
	| LC    | openmodscore             | 0.12.2                  | minecraft.jar                                          | None                                     |
	| LC    | skinlayers3d             | 1.2.0                   | 3dSkinLayers-forge-mc1.12.2-1.2.0.jar                  | None                                     |
	| LC    | equipmentcompare         | 1.3.3                   | EquipmentCompare-1.12.2-1.3.4.jar                      | None                                     |
	| LC    | securitycraft            | v1.9.8                  | [1.12.2] SecurityCraft v1.9.8.jar                      | None                                     |
	| LC    | supermartijn642corelib   | 1.1.15                  | _supermartijn642corelib-1.1.15-forge-mc1.12.jar        | None                                     |
	| LC    | aether_legacy            | 1.5.3.2                 | aether-1.12.2-v1.5.3.2.jar                             | None                                     |
	| LC    | aiimprovements           | 0.0.1.3                 | AIImprovements-1.12-0.0.1b3.jar                        | None                                     |
	| LC    | crafttweaker             | 4.1.20                  | CraftTweaker2-1.12-4.1.20.689.jar                      | None                                     |
	| LC    | jei                      | 4.16.1.1003             | jei_1.12.2-4.16.1.1003.jar                             | None                                     |
	| LC    | appleskin                | 1.0.14                  | AppleSkin-mc1.12-1.0.14.jar                            | None                                     |
	| LC    | baubles                  | 1.5.2                   | Baubles-1.12-1.5.2.jar                                 | None                                     |
	| LC    | artifacts                | 1.12.2-1.2.3            | Artifacts-1.12.2-1.2.3.jar                             | None                                     |
	| LC    | quark                    | r1.6-179                | Quark-r1.6-179.jar                                     | None                                     |
	| LC    | autoreglib               | 1.3-32                  | AutoRegLib-1.3-32.jar                                  | None                                     |
	| LC    | bno                      | 1.12.2-1.0.4.0          | BasicNetherOres-1.12.2-1.0.5.0.jar                     | None                                     |
	| LC    | bettercaves              | 1.12.2                  | bettercaves-1.12.2-2.0.4.jar                           | None                                     |
	| LC    | betterfurnacesreforged   | 1.5.5                   | BetterFurnacesReforged-1.12.2-1.5.5.jar                | None                                     |
	| LC    | bettermineshafts         | 1.12.2-2.2.1            | BetterMineshaftsForge-1.12.2-2.2.1.jar                 | None                                     |
	| LC    | byg                      | 1.7.1                   | BiomesYouGo1.7.1.jar                                   | None                                     |
	| LC    | bookshelf                | 2.3.590                 | Bookshelf-1.12.2-2.3.590.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | bookworm                 | 1.12.2-2.5.2.1          | bookworm-1.12.2-2.5.2.1.jar                            | None                                     |
	| LC    | buildcraftlib            | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                           | None                                     |
	| LC    | buildcraftcore           | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                           | None                                     |
	| LC    | buildcraftbuilders       | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                           | None                                     |
	| LC    | buildcrafttransport      | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                           | None                                     |
	| LC    | buildcraftsilicon        | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                           | None                                     |
	| LC    | theoneprobe              | 1.4.28                  | theoneprobe-1.12-1.4.28.jar                            | None                                     |
	| LC    | buildcraftcompat         | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                           | None                                     |
	| LC    | buildcraftenergy         | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                           | None                                     |
	| LC    | buildcraftfactory        | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                           | None                                     |
	| LC    | buildcraftrobotics       | 7.99.24.8               | buildcraft-all-7.99.24.8.jar                           | None                                     |
	| LC    | carryon                  | 1.12.3                  | carryon-1.12.2-1.12.7.23.jar                           | None                                     |
	| LC    | chococraft               | 0.9.1.52                | chococraft_1.12.1-0.9.1.52.jar                         | None                                     |
	| LC    | clumps                   | 3.1.2                   | Clumps-3.1.2.jar                                       | None                                     |
	| LC    | controlling              | 3.0.10                  | Controlling-3.0.12.2.jar                               | None                                     |
	| LC    | ctgui                    | 1.0.0                   | CraftTweaker2-1.12-4.1.20.689.jar                      | None                                     |
	| LC    | crafttweakerjei          | 2.0.3                   | CraftTweaker2-1.12-4.1.20.689.jar                      | None                                     |
	| LC    | creativecore             | 1.10.0                  | CreativeCore_v1.10.71_mc1.12.2.jar                     | None                                     |
	| LC    | customnpcs               | 1.12                    | CustomNPCs_1.12.2-(05Jul20).jar                        | None                                     |
	| LC    | ptrmodellib              | 1.0.5                   | PTRLib-1.0.5.jar                                       | None                                     |
	| LC    | props                    | 2.6.3.7                 | Decocraft-2.6.3.7_1.12.2.jar                           | None                                     |
	| LC    | mocreatures              | 12.0.5                  | DrZharks+MoCreatures+Mod-12.0.5.jar                    | None                                     |
	| LC    | mclib                    | 2.4.2                   | mclib-2.4.2-1.12.2.jar                                 | None                                     |
	| LC    | emoticons                | 1.1.2                   | emoticons-1.1.2-1.12.2.jar                             | None                                     |
	| LC    | eplus                    | 5.0.179                 | EnchantingPlus-1.12.2-5.0.179.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | enchdesc                 | 1.1.15                  | EnchantmentDescriptions-1.12.2-1.1.15.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | endreborn                | 0.3.8                   | EndReborn+[0.3.9].jar                                  | None                                     |
	| LC    | epicfight                | 1.12.2-2.2.8            | EpicFightMod-1.12.2-2.2.8.jar                          | None                                     |
	| LC    | umm3185118519            | release 1.5 - MC 1.12.2 | Extended+ItemsOres+[1.12.2]+(release+1.5).jar          | None                                     |
	| LC    | forgelin                 | 1.8.4                   | Forgelin-1.8.4.jar                                     | None                                     |
	| LC    | futuremc                 | 0.2.6                   | future-mc-0.2.11.jar                                   | None                                     |
	| LC    | grapplemod               | 1.12.2-v13              | grappling_hook_mod-1.12.2-v13.jar                      | None                                     |
	| LC    | gravestone               | 1.10.3                  | gravestone-1.10.3.jar                                  | None                                     |
	| LC    | ichunutil                | 7.2.2                   | iChunUtil-1.12.2-7.2.2.jar                             | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | hats                     | 7.1.1                   | Hats-1.12.2-7.1.1.jar                                  | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | infwithmend              | 1.0.0                   | infwithmend-forge-1.12.2-1.0.0.jar                     | None                                     |
	| LC    | ironchest                | 1.12.2-7.0.67.844       | ironchest-1.12.2-7.0.72.847.jar                        | None                                     |
	| LC    | jeresources              | 0.9.2.60                | JustEnoughResources-1.12.2-0.9.2.60.jar                | None                                     |
	| LC    | legendarytooltips        | 1.1.9                   | LegendaryTooltips-1.12.2-1.1.10.jar                    | None                                     |
	| LC    | letmedespawn             | 1.0                     | letmedespawn-1.12.2-forge-1.0.2.jar                    | None                                     |
	| L     | littleframes             | 1.0.0                   | LittleFrames_WATERMEDIA_(by_Blake)_v1.1.2_mc1.12.2.jar | None                                     |
	| L     | lootr                    | 0.6.2                   | lootr-1.12.2-0.6.2.jar                                 | None                                     |
	| L     | mantle                   | 1.12-1.3.3.55           | Mantle-1.12-1.3.3.55.jar                               | None                                     |
	| L     | mekanism                 | 1.12.2-9.8.3.390        | Mekanism-1.12.2-9.8.3.390.jar                          | None                                     |
	| L     | mekanismgenerators       | 1.12.2-9.8.3.390        | MekanismGenerators-1.12.2-9.8.3.390.jar                | None                                     |
	| L     | mekanismtools            | 1.12.2-9.8.3.390        | MekanismTools-1.12.2-9.8.3.390.jar                     | None                                     |
	| L     | morpheus                 | 1.12.2-3.5.106          | Morpheus-1.12.2-3.5.106.jar                            | None                                     |
	| L     | mousetweaks              | 2.10.1                  | MouseTweaks-2.10.1-mc1.12.2.jar                        | None                                     |
	| L     | supermartijn642configlib | 1.1.6                   | supermartijn642configlib-1.1.8-forge-mc1.12.jar        | None                                     |
	| L     | movingelevators          | 1.4.4                   | movingelevators-1.4.4-forge-mc1.12.jar                 | None                                     |
	| L     | mutantbeasts             | 1.12.2-1.0.2            | MutantBeasts-1.12.2-1.0.2.jar                          | None                                     |
	| L     | msic                     | 1.0                     | MyServerIsCompatible-1.12.2-1.0.jar                    | None                                     |
	| L     | openmods                 | 0.12.2                  | OpenModsLib-1.12.2-0.12.2.jar                          | None                                     |
	| L     | openblocks               | 1.8.1                   | OpenBlocks-1.12.2-1.8.1.jar                            | None                                     |
	| L     | overpoweredarmorbar      | @VERSION@               | overloadedarmorbar-1.0.4g.jar                          | None                                     |
	| L     | patchouli                | 1.0-23.6                | Patchouli-1.0-23.6.jar                                 | None                                     |
	| L     | rawinput                 | 1.4.2                   | rawinput-1.12.2-1.4.2.jar                              | None                                     |
	| L     | refinedstorage           | 1.6.16                  | refinedstorage-1.6.16.jar                              | None                                     |
	| L     | roguelike                | 1.8.0                   | RoguelikeDungeons-1.12.2-1.8.0.jar                     | None                                     |
	| L     | silentlib                | 3.0.13                  | SilentLib-1.12.2-3.0.14+168.jar                        | None                                     |
	| L     | scalinghealth            | 1.3.37                  | ScalingHealth-1.12.2-1.3.42+147.jar                    | None                                     |
	| L     | simplelogin              | 1.2.4-beta+build127     | simplelogin-1.2.4-beta+build127.jar                    | None                                     |
	| L     | tconstruct               | 1.12.2-2.13.0.183       | TConstruct-1.12.2-2.13.0.183.jar                       | None                                     |
	| L     | tetra                    | 0.39.1                  | tetra-1.12.2-0.39.1.jar                                | None                                     |
	| L     | torchmaster              | 1.8.5.0                 | torchmaster_1.12.2-1.8.5.0.jar                         | None                                     |
	| L     | travelersbackpack        | 1.0.35                  | TravelersBackpack-1.12.2-1.0.35.jar                    | None                                     |
	| L     | tbintegration            | 1.0.1                   | TravelersBackpackIntegration-1.12.2-1.0.1.jar          | None                                     |
	| L     | voicechat                | 1.12.2-2.4.26           | voicechat-forge-1.12.2-2.4.26.jar                      | None                                     |
	| L     | waystones                | 4.1.0                   | Waystones_1.12.2-4.1.0.jar                             | None                                     |
	| L     | xaerominimap             | 23.8.0                  | Xaeros_Minimap_23.8.0_Forge_1.12.jar                   | None                                     |
	| L     | xaeroworldmap            | 1.34.1                  | XaerosWorldMap_1.34.1_Forge_1.12.jar                   | None                                     |
	| L     | zawa                     | 1.12.2-2.1.3            | zawa-1.12.2-2.1.3.jar                                  | None                                     |
	| UD    | mclib_core               | 2.4.2                   | minecraft.jar                                          | None                                     |

	Loaded coremods (and transformers): 
MSICCoreMod (MyServerIsCompatible-1.12.2-1.0.jar)
  
SecurityCraftLoadingPlugin ([1.12.2] SecurityCraft v1.9.8.jar)
  
McLib core mod (mclib-2.4.2-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
FutureMC (future-mc-0.2.11.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
Moving Elevators Plugin (movingelevators-1.4.4-forge-mc1.12.jar)
  
XaeroMinimapPlugin (Xaeros_Minimap_23.8.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerMPTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.MinecraftServerTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
LootrCore (lootr-1.12.2-0.6.2.jar)
  
MixinBooter (!mixinbooter-8.6.jar)
  
CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  
SuperMartijn642's Core Lib Plugin (_supermartijn642corelib-1.1.15-forge-mc1.12.jar)
  
infwithmend (infwithmend-forge-1.12.2-1.0.0.jar)
  
Let Me Despawn (letmedespawn-1.12.2-forge-1.0.2.jar)
  
XaeroWorldMapPlugin (XaerosWorldMap_1.34.1_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.EntityPlayerMPTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.SaveFormatTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
  xaero.map.core.transformer.MinecraftServerTransformer
  xaero.map.core.transformer.MinecraftTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 23.9.2.230827' Renderer: 'AMD Radeon(TM) Graphics'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) Graphics GL version 4.6.0 Compatibility Profile Context 23.9.2.230827, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, quark:emote_resources (incompatible), file/VisibleOres1.5.zip, file/Default-Dark-Mode-1.16-2023.7.0.zip
	Current Language: Español (España)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 5600G with Radeon Graphics 
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 Compatibility Profile Context 23.9.2.230827
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by SrRapero720** [comment]
you need to install LittleTiles
