### ISSUE TITLE
Little Tiles And Size

### ISSUE THREAD

**Issue by Longshot133** [CreativeMD/LittleFrames#64]
Would it be possible to have the frame have more fine size changes? such as when you go below 1 it instantely goes to .01 but having more intervals would be nice.

(Second part)
This in addition to having the ability to use in little tile spaces would be amazing. (if this already can be i apologize, i am running in 1.12.2)

Thought these may be cool if possible at all, was makin some pc's for quests and thought this mod would be neat if it could do dem. sorry to bother!

**Comment by CreativeMD** [comment]
Second part already exist (you can craft one using the structure builder). And you can do finer changes, you can type in any number you want to. Sorry for responding that late. I somehow missed this issue (or forgot to respond).
