### ISSUE TITLE
[1.19.2] Java crash when loading chunks with little frames

### ISSUE THREAD

**Issue by flangopink** [CreativeMD/LittleFrames#66]
Placed little frames on another pc and it worked fine. Joined the server on my home pc, and i get an "EXCEPTION_ACCESS_VIOLATION" crash whenever the chunk with little frames is loaded.
The modpack is 1.19.2 Forge with Rubidium and other mods installed.
VLC option is disabled, only .jpg and .gif images are uploaded.

Crash log: https://pastebin.com/FU8ewfft

Edit:
The images on the screenshot load fine with a very small render distance, but there's a very long .gif littleframe in the chunk behind them, which probably causes the crash.

This is what i see before the crash happens:
![image](https://github.com/CreativeMD/LittleFrames/assets/48758448/37033a16-3f5a-4cc5-b701-e5e310ff89f5)

**Comment by SrRapero720** [comment]
Try removing rubidium and use Embeddium instead.
If the problem persist... Send crash report again

**Comment by flangopink** [comment]
Can't remove rubidium as it's in a server modpack. Had to ask other players to break the culprit littleframe. Still not sure why it causes crashes.

**Comment by CreativeMD** [comment]
Can you provide the link to the gif file, so we can do some testing on our own?

**Comment by CreativeMD** [comment]
Is this still an issue?

**Comment by CreativeMD** [comment]
I will close this for now. If this is still a thing, please provide the information necessary here and I will reopen the issue.
