### ISSUE TITLE
I don´t see the image?

### ISSUE THREAD

**Issue by LuisDaAS** [CreativeMD/LittleFrames#67]
Hi, I am in the 1.20.1, put the link of an Imgur image and the frame puts black and don't show the image. I have to wait a couple of minutes or it´s a bug/error?

**Comment by CreativeMD** [comment]
Make sure to link the actual image and the website containing the image. If you open the url you should only see the picture nothing else. Usually the url should end with .jpg or .png. The best way to achieve this is to right click the image and hit copy image address.
