### ISSUE TITLE
local gif and images dont work

### ISSUE THREAD

**Issue by MoviVadumee** [CreativeMD/LittleFrames#68]
video links work great but local files don't. I entered the file path for a gif in a file on my desktop and nothing at all came up. just the wooden frame. is there a specific file the local images need to be?
![2023-11-14_15 36 40](https://github.com/CreativeMD/LittleFrames/assets/147354486/ba64d9b6-0577-4b53-bc00-d54796a1c368)

**Comment by SrRapero720** [comment]
you need to use ``file:///`` at the start to get local files working (applies to 1.12.2 and 1.20.1)
