### ISSUE TITLE
Images don't work

### ISSUE THREAD

**Issue by 0xy49** [CreativeMD/LittleFrames#69]
Images don't work with message "Could not download image" but video work perfectly

I use LittleFrames_Forge_v1.3.3_mc1.20.1.jar with watermedia_2.0.11.jar and CreativeCore_Forge_v2.11.10_mc1.20.1.jar on minecraft server 1.20.1
Forge version is 47.2.6

**Comment by 0xy49** [comment]
![2023-11-19_23 44 26](https://github.com/CreativeMD/LittleFrames/assets/151474559/dc5c55a5-7ee1-41c9-bf5f-d046705944b6)

**Comment by SrRapero720** [comment]
WATERMeDIA issue, already fixed on 2.0.21
