### ISSUE TITLE
Minecraft Crashes Instantly when trying to play a Video on Ubuntu 20.10

### ISSUE THREAD

**Issue by xsigsig** [CreativeMD/LittleFrames#7]
https://pastebin.com/6FWquLEU

**Comment by CreativeMD** [comment]
Your pastebin link is private.

**Comment by xsigsig** [comment]
[hs_err_pid10623.log](https://github.com/CreativeMD/LittleFrames/files/5895263/hs_err_pid10623.log)
My pastebin is pending moderation for some reason, probably because I made it only 7 hours ago
I hope a log file is okay

**Comment by xsigsig** [comment]
If log file not okay, pastebin upload should be visible now

**Comment by CreativeMD** [comment]
Honestly, I have no idea what is happening there. Never tested it on linux ... in theory it should work, but obviously something is wrong. There is no obvious error in your log ... so I can't even contact vlcj for help. Can you try to remove VLC and run this mod again? That maybe helps to see why it crashes.

**Comment by xsigsig** [comment]
I've gone through a long process trying to solve the problem to this issue
So far, when I load mp4 files it works flawlessly, but whenever it's a YouTube video it crashes instantly.
I uninstalled VLC with apt-get and no crashed with YouTube which makes sense
I tried installing VLC using snap instead since that's the preferred installation method, LittleFrames didn't even notice VLC existed which means it can only find VLC if it's installed with apt-get
I reinstalled VLC with apt-get to see if it was a bad install and YouTube still crashed it
I then installed Ubuntu 20.04.1LTS to see if it would solve the issue
I installed VLC with apt-get, ran minecraft with your mods, and YouTube ran perfectly
So it's could be that VLC or VLCJ has bad support for 20.10, so you can decide if this should be an open issue or not

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. I will keep the issue in mind, but I doubt I can do something about it. Thank you very much for your detailed information (might help other people)!
