### ISSUE TITLE
1.12.2 Game Crashes with "Uknown error" after installing Little Frames.

### ISSUE THREAD

**Issue by MoonieGlare** [CreativeMD/LittleFrames#70]
I have a modpack with a bunch of mods and whenever I install any version of little frames, this occurs. 

---- Minecraft Crash Report ----

// You're mean.

Time: 2023-11-22 21:56:36 GMT
Description: Initializing game

java.lang.NoClassDefFoundError: team/creative/littleframes/LittleFrames$1
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
    at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: team.creative.littleframes.LittleFrames$1
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
    ... 38 more
Caused by: java.lang.NoClassDefFoundError: com/creativemd/littletiles/client/gui/handler/LittleStructureGuiHandler
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 40 more
Caused by: java.lang.ClassNotFoundException: com.creativemd.littletiles.client.gui.handler.LittleStructureGuiHandler
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
    ... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 11 (amd64) version 10.0
  Java Version: 1.8.0_372, Azul Systems, Inc.
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
  Memory: 1132499352 bytes (1080 MB) / 1873805312 bytes (1787 MB) up to 7635730432 bytes (7282 MB)
  JVM Flags: 4 total; -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 85 mods loaded, 84 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                   | Version               | Source                                             | Signature                                |
       |:----- |:-------------------- |:--------------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LC    | minecraft            | 1.12.2                | minecraft.jar                                      | None                                     |
       | LC    | mcp                  | 9.42                  | minecraft.jar                                      | None                                     |
       | LC    | FML                  | 8.0.99.99             | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LC    | forge                | 14.23.5.2859          | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LC    | creativecoredummy    | 1.0.0                 | minecraft.jar                                      | None                                     |
       | LC    | otgcore              | 1.12.2-v9.4           | minecraft.jar                                      | None                                     |
       | LC    | xaerominimap_core    | 1.12.2-1.0            | minecraft.jar                                      | None                                     |
       | LC    | xaeroworldmap_core   | 1.12.2-1.0            | minecraft.jar                                      | None                                     |
       | LC    | foamfixcore          | 7.7.4                 | minecraft.jar                                      | None                                     |
       | LC    | redstoneflux         | 2.1.1                 | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
       | LC    | cofhcore             | 4.6.6                 | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
       | LC    | libvulpes            | 0.4.2.-25             | LibVulpes-1.12.2-0.4.2-25-universal.jar            | None                                     |
       | LC    | advancedrocketry     | 1.12.2-2.0.0-13       | AdvancedRocketry-1.12.2-2.0.0-13.jar               | None                                     |
       | LC    | animalium            | 0.3.8                 | Animalium-0.3.8.jar                                | None                                     |
       | LC    | craftstudioapi       | 1.0.0                 | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
       | LC    | openterraingenerator | v9.4                  | OpenTerrainGenerator-1.12.2-v9.4.jar               | None                                     |
       | LC    | animania             | 2.0.3.28              | animania-1.12.2-base-2.0.3.28.jar                  | None                                     |
       | LC    | jei                  | 4.16.1.1001           | jei_1.12.2-4.16.1.1001.jar                         | None                                     |
       | LC    | quark                | r1.6-179              | Quark-r1.6-179.jar                                 | None                                     |
       | LC    | autoreglib           | 1.3-32                | AutoRegLib-1.3-32.jar                              | None                                     |
       | LC    | baubles              | 1.5.2                 | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LC    | forgelin             | 1.8.2                 | Forgelin-1.8.2.jar                                 | None                                     |
       | LC    | betterfoliage        | 2.3.2                 | BetterFoliage-MC1.12-2.3.3.jar                     | None                                     |
       | LC    | betternether         | 0.1.8.6               | betternether-0.1.8.6.jar                           | None                                     |
       | LC    | biomebundle          | 5.1                   | Biome_Bundle-1.12.2-v6.1.jar                       | None                                     |
       | LC    | carryon              | 1.12.3                | carryon-1.12.2-1.12.6.20.jar                       | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
       | LC    | ctm                  | MC1.12.2-1.0.2.31     | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
       | LC    | chisel               | MC1.12.2-1.0.2.45     | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
       | LC    | codechickenlib       | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LC    | cofhworld            | 1.4.0                 | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
       | LC    | controlling          | 3.0.10                | Controlling-3.0.12.2.jar                           | None                                     |
       | LC    | extendedrenderer     | v1.0                  | coroutil-1.12.1-1.2.37.jar                         | None                                     |
       | LC    | coroutil             | 1.12.1-1.2.37         | coroutil-1.12.1-1.2.37.jar                         | None                                     |
       | LC    | configmod            | v1.0                  | coroutil-1.12.1-1.2.37.jar                         | None                                     |
       | LC    | corpse               | 1.12.2-1.0.8          | corpse-1.12.2-1.0.8.jar                            | None                                     |
       | LC    | creativecore         | 1.10.0                | CreativeCore_v1.10.71_mc1.12.2.jar                 | None                                     |
       | LC    | sereneseasons        | 1.2.18                | SereneSeasons-1.12.2-1.2.18-universal.jar          | None                                     |
       | LC    | orelib               | 3.6.0.1               | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LC    | dsurround            | 3.6.1.0               | DynamicSurroundings-1.12.2-3.6.1.0.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LC    | silentlib            | 3.0.13                | SilentLib-1.12.2-3.0.14+168.jar                    | None                                     |
       | LC    | extendeddays         | 0.2.9                 | ExtendedDays-1.12.2-0.2.9-28.jar                   | None                                     |
       | LC    | foamfix              | @VERSION@             | foamfix-0.10.15-1.12.2.jar                         | None                                     |
       | LC    | llibrary             | 1.7.20                | llibrary-1.7.20-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LC    | fossil               | 8.0.5                 | fossilsarcheology-8.0.5.jar                        | None                                     |
       | LC    | cfm                  | 6.3.0                 | furniture-6.3.2-1.12.2.jar                         | None                                     |
       | LC    | grapplemod           | 1.12.2-v12.3          | grapplemod-1.12.2-v12.3.jar                        | None                                     |
       | LC    | hardcoredarkness     | 2.0                   | HardcoreDarkness-MC1.12.2-2.0.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LC    | hbm                  | hbm-1.8.3a-G          | hbm-1.8.3a-G.jar                                   | None                                     |
       | LC    | waila                | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | L     | littleframes         | 1.0.0                 | LittleFrames_v1.0.12_mc1.12.2.jar                  | None                                     |
       | L     | malisiscore          | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
       | L     | malisisdoors         | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
       | L     | mca                  | 6.1.0                 | MCA-1.12.2-6.1.0-universal.jar                     | None                                     |
       | L     | mekanism             | 1.12.2-9.8.3.390      | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
       | L     | mekanismgenerators   | 1.12.2-9.8.3.390      | MekanismGenerators-1.12.2-9.8.3.390.jar            | None                                     |
       | L     | mekanismtools        | 1.12.2-9.8.3.390      | MekanismTools-1.12.2-9.8.3.390.jar                 | None                                     |
       | L     | moreplayermodels     | 1.12.2                | MorePlayerModels_1.12.2-(05Dec19).jar              | None                                     |
       | L     | particleculling      | v1.4.1                | particleculling-1.12.2-v1.4.1.jar                  | None                                     |
       | L     | peacefulsurface      | 1.12.2-v2             | PeacefulSurface-1.12.2-v2.jar                      | None                                     |
       | L     | performant           | 1.12.2-1.5            | performant-1.11.jar                                | None                                     |
       | L     | playerrevive         | 1.0                   | PlayerRevive_v1.2.40_mc1.12.2.jar                  | None                                     |
       | L     | refinedstorage       | 1.6.16                | refinedstorage-1.6.16.jar                          | None                                     |
       | L     | simpleplanes         | 3.0.1.7               | simpleplanes-1.12.2-3.0.1.7.jar                    | None                                     |
       | L     | bedsaynosleep        | 1.0.0                 | Sleepn't+V2+1.12.2.jar                             | None                                     |
       | L     | soundfilters         | 0.12.1_for_1.12       | SoundFilters-0.12.1_for_1.12.jar                   | None                                     |
       | L     | surge                | 2.0.79                | Surge-1.12.2-2.0.79.jar                            | None                                     |
       | L     | texfix               | 4.0                   | TexFix+V-1.12-4.0.jar                              | None                                     |
       | L     | thermalfoundation    | 2.6.7                 | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
       | L     | thermalexpansion     | 5.5.7                 | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
       | L     | thermalcultivation   | 0.3.6                 | ThermalCultivation-1.12.2-0.3.6.1-universal.jar    | None                                     |
       | L     | thermaldynamics      | 2.5.6                 | ThermalDynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |
       | L     | thermalinnovation    | 0.3.6                 | ThermalInnovation-1.12.2-0.3.6.1-universal.jar     | None                                     |
       | L     | thutcore             | 5.21.0                | thutcore-1.12.2-5.21.0.jar                         | None                                     |
       | L     | thutcore_compat      | 1.0                   | thutcore-1.12.2-5.21.0.jar                         | None                                     |
       | L     | thuttech             | 6.1.6                 | thuttech-1.12.2-6.1.6.jar                          | None                                     |
       | L     | uteamcore            | 2.2.5.226             | u_team_core-1.12.2-2.2.5.226.jar                   | None                                     |
       | L     | usefulbackpacks      | 1.5.4.85              | useful_backpacks-1.12.2-1.5.4.85.jar               | None                                     |
       | L     | vanillafix           | 1.0.10-150            | VanillaFix-1.0.10-150.jar                          | None                                     |
       | L     | gvc                  | 1.2.5                 | Voice+Chat+Reloaded-1.2.5.jar                      | None                                     |
       | L     | watermedia           | 2.0.5                 | watermedia-2.0.5.jar                               | None                                     |
       | L     | weather2             | 1.12.1-2.6.12         | weather2-1.12.1-2.6.12.jar                         | None                                     |
       | L     | xaerominimap         | 23.8.4                | Xaeros_Minimap_23.8.4_Forge_1.12.jar               | None                                     |
       | L     | xaeroworldmap        | 1.36.0                | XaerosWorldMap_1.36.0_Forge_1.12.jar               | None                                     |
       | L     | phosphor-lighting    | 1.12.2-0.2.7          | phosphor-forge-mc1.12.2-0.2.7-universal.jar        | None                                     |
       | UD    | advancedrocketrycore | 1                     | minecraft.jar                                      | None                                     |
  Loaded coremods (and transformers): TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.4.1.jar)
                                        
                                      XaeroWorldMapPlugin (XaerosWorldMap_1.36.0_Forge_1.12.jar)
                                        xaero.map.core.transformer.ChunkTransformer
                                        xaero.map.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.map.core.transformer.EntityPlayerTransformer
                                        xaero.map.core.transformer.AbstractClientPlayerTransformer
                                        xaero.map.core.transformer.WorldClientTransformer
                                        xaero.map.core.transformer.EntityPlayerMPTransformer
                                        xaero.map.core.transformer.PlayerListTransformer
                                        xaero.map.core.transformer.SaveFormatTransformer
                                        xaero.map.core.transformer.BiomeColorHelperTransformer
                                        xaero.map.core.transformer.MinecraftServerTransformer
                                        xaero.map.core.transformer.MinecraftTransformer
                                      MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
                                        
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      CWGFarPlaneViewCoreMod (CWGFarPlaneView-0.4.0-core.jar)
                                        cwgfarplaneview.core.CWGFPVClassTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-2.0.0-13.jar)
                                        zmaster587.advancedRocketry.asm.ClassTransformer
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.3.3.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      XaeroMinimapPlugin (Xaeros_Minimap_23.8.4_Forge_1.12.jar)
                                        xaero.common.core.transformer.ChunkTransformer
                                        xaero.common.core.transformer.NetHandlerPlayClientTransformer
                                        xaero.common.core.transformer.EntityPlayerTransformer
                                        xaero.common.core.transformer.AbstractClientPlayerTransformer
                                        xaero.common.core.transformer.WorldClientTransformer
                                        xaero.common.core.transformer.EntityPlayerMPTransformer
                                        xaero.common.core.transformer.EntityPlayerSPTransformer
                                        xaero.common.core.transformer.PlayerListTransformer
                                        xaero.common.core.transformer.SaveFormatTransformer
                                        xaero.common.core.transformer.GuiIngameForgeTransformer
                                        xaero.common.core.transformer.MinecraftServerTransformer
                                        xaero.common.core.transformer.GuiBossOverlayTransformer
                                        xaero.common.core.transformer.ModelRendererTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 546.01' Renderer: 'NVIDIA GeForce GTX 1650/PCIe/SSE2'
  Suspected Mods: Unknown
  Launched Version: 1.12.2
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.01, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Ephuya (incompatible)
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 12x 12th Gen Intel(R) Core(TM) i5-12400F

**Comment by SrRapero720** [comment]
LittleTiles is MISSING, and is a required mod on 1.12.2
https://www.curseforge.com/minecraft/mc-mods/littletiles
