### ISSUE TITLE
[Feature Request] Save settings from previous placement

### ISSUE THREAD

**Issue by DN2048** [CreativeMD/LittleFrames#71]
**Description:**
When placing a lot of LittleFrames in the same place you tend to use the same settings (brightness, alpha, both side, etc).
It would useful if the default values when placing a new frame would be from the previously saved one.

**Ideas to implement:**
- Have a new checkbox on the GUI to "also save settings" when pressing the save button.
- Setting on the json file (client only) if you want to save the settings when placing.

**Comment by CreativeMD** [comment]
If you are in creative mod you can do that quite easily. Just hold down CTRL when using the block pick function (mouse wheel by default), this will store the block data. Once you place it the settings will restored. This is a vanilla function and works with blocks like furnaces as well. I think that should be enough in your case.

**Comment by DN2048** [comment]
Cool! I didn't know you could do that. Tested and works. Thanks.
