### ISSUE TITLE
Game crashes when i join server/map

### ISSUE THREAD

**Issue by ZeTaX2002** [CreativeMD/LittleFrames#72]
The game crashed whilst tesselating block model
Error: java.lang.NoClassDefFoundError: net/minecraftforge/common/model/TRSRTransformation$1

---- Minecraft Crash Report ----

WARNING: coremods are present:
  WolfArmorCore (WolfArmorAndStorage-1.12.2-3.8.0-universal-signed.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  McLib core mod (mclib-2.4.2-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
  FutureMC (future-mc-0.2.11.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.8.jar)
  CustomSkinLoader (CustomSkinLoader_ForgeLegacy-14.19.1.jar)
  LittlePatchingLoader (LittleTiles_v1.5.85_mc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 1/3/24 1:09 AM
Description: Tesselating block model

java.lang.NoClassDefFoundError: net/minecraftforge/common/model/TRSRTransformation$1
	at net.minecraftforge.common.model.TRSRTransformation.getRotation(TRSRTransformation.java:150)
	at net.minecraftforge.common.model.TRSRTransformation.from(TRSRTransformation.java:138)
	at net.blay09.mods.cookingforblockheads.client.LowerableFacingOnDemandModel.func_188616_a(LowerableFacingOnDemandModel.java:39)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:145)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:65)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:79)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:58)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.model.TRSRTransformation$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
Caused by: java.lang.SecurityException: class "net.minecraftforge.common.model.TRSRTransformation$1"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.common.model.TRSRTransformation.getRotation(TRSRTransformation.java:150)
	at net.minecraftforge.common.model.TRSRTransformation.from(TRSRTransformation.java:138)
	at net.blay09.mods.cookingforblockheads.client.LowerableFacingOnDemandModel.func_188616_a(LowerableFacingOnDemandModel.java:39)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187497_c(BlockModelRenderer.java:145)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:65)

-- Block model being tesselated --
Details:
	Block: cookingforblockheads:cutting_board[facing=east,lowered=false]
	Block location: World: (-247,62,1016), Chunk: (at 9,3,8 in -16,63; contains blocks -256,0,1008 to -241,255,1023), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Using AO: false
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:79)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:58)

-- Block being tesselated --
Details:
	Block type: ID #895 (tile.cookingforblockheads:cutting_board // net.blay09.mods.cookingforblockheads.block.BlockCuttingBoard // cookingforblockheads:cutting_board)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (-247,62,1016), Chunk: (at 9,3,8 in -16,63; contains blocks -256,0,1008 to -241,255,1023), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['KuroNekoVT'/6425, l='MpServer', x=-126.02, y=87.00, z=1009.92]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-98,93,1005), Chunk: (at 14,5,13 in -7,62; contains blocks -112,0,992 to -97,255,1007), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
	Level time: 8895015 game time, 950045 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 79 total; [EntityPlayerSP['KuroNekoVT'/6425, l='MpServer', x=-126.02, y=87.00, z=1009.92], EntityBlackSpiderMonkey['Black Spider Monkey'/512, l='MpServer', x=-66.60, y=77.00, z=1115.40], EntityLatchedRenderer['Entidad desconocida'/1, l='MpServer', x=8.50, y=65.00, z=8.50], EntityTippedArrow['Flecha'/6674, l='MpServer', x=-183.17, y=70.02, z=949.38], EntityItem['item.item.animalium.wild_dog_pelt'/1813, l='MpServer', x=-174.81, y=67.00, z=960.01], EntityItem['item.item.bush_meat_raw'/2840, l='MpServer', x=-90.80, y=83.00, z=993.88], EntityItem['item.item.fur'/2841, l='MpServer', x=-91.88, y=82.00, z=992.59], EntityItem['item.item.rottenFlesh'/5149, l='MpServer', x=-146.54, y=71.00, z=1043.51], EntityZombieVillager['Aldeano zombi'/4385, l='MpServer', x=-90.50, y=26.00, z=1067.50], EntitySkeleton['Esqueleto'/5410, l='MpServer', x=-203.27, y=30.00, z=1021.50], EntityCustomNpc['Guardia'/291, l='MpServer', x=-173.37, y=68.00, z=1053.20], EntitySpider['Araña'/5156, l='MpServer', x=-81.50, y=18.00, z=989.50], EntityBlackSpiderMonkey['Black Spider Monkey'/550, l='MpServer', x=-42.55, y=101.00, z=1054.65], EntitySkeleton['Esqueleto'/6184, l='MpServer', x=-180.23, y=45.00, z=933.47], EntityBlackSpiderMonkey['Black Spider Monkey'/563, l='MpServer', x=-26.40, y=92.00, z=1048.60], EntityCustomNpc['Guardia'/309, l='MpServer', x=-157.50, y=81.00, z=996.42], EntityCustomNpc['Guardia'/313, l='MpServer', x=-159.68, y=73.00, z=1029.71], EntitySkeleton['Esqueleto'/6203, l='MpServer', x=-76.53, y=25.00, z=1052.27], EntityCreeper['Creeper'/6204, l='MpServer', x=-75.50, y=24.00, z=1048.50], EntitySpider['Araña'/6220, l='MpServer', x=-196.50, y=43.00, z=937.50], EntityWildDog['Wild Dog'/6222, l='MpServer', x=-192.50, y=43.00, z=942.50], EntityZombie['Zombi'/6224, l='MpServer', x=-197.50, y=43.00, z=940.50], EntityZombie['Zombi'/6225, l='MpServer', x=-193.50, y=43.00, z=940.50], EntityItem['item.item.animalium.rat_meat'/5713, l='MpServer', x=-112.64, y=70.00, z=1058.13], EntityCustomNpc['Guardia'/340, l='MpServer', x=-142.81, y=71.00, z=1060.34], EntityItem['item.item.sulphur'/5717, l='MpServer', x=-163.69, y=76.00, z=988.64], EntityZombie['Zombi'/6230, l='MpServer', x=-128.50, y=14.00, z=1070.50], EntityWildDog['Wild Dog'/6497, l='MpServer', x=-228.50, y=71.00, z=973.50], EntityWildDog['Wild Dog'/6499, l='MpServer', x=-228.50, y=71.00, z=974.50], EntityZombie['Zombi'/6245, l='MpServer', x=-46.50, y=77.00, z=963.50], EntityCreeper['Creeper'/5734, l='MpServer', x=-184.50, y=29.00, z=941.50], EntityPufferFish['Pufferfish'/358, l='MpServer', x=-113.85, y=48.82, z=934.55], EntityCreeper['Creeper'/3432, l='MpServer', x=-71.45, y=46.00, z=1058.17], EntitySkeleton['Esqueleto'/5742, l='MpServer', x=-127.50, y=14.00, z=1072.50], EntityCreeper['Creeper'/6260, l='MpServer', x=-78.50, y=26.00, z=1064.50], EntityZombieVillager['Aldeano zombi'/6261, l='MpServer', x=-150.50, y=60.00, z=1070.50], EntityCustomNpc['Guardia'/375, l='MpServer', x=-109.32, y=70.00, z=1057.42], EntitySkeleton['Esqueleto'/4219, l='MpServer', x=-133.50, y=18.00, z=1076.50], EntityPainting['Cuadro'/6527, l='MpServer', x=-244.00, y=64.00, z=1011.03], EntitySkeleton['Esqueleto'/3970, l='MpServer', x=-114.50, y=32.00, z=1038.50], EntityWildDog['Wild Dog'/6790, l='MpServer', x=-159.50, y=45.00, z=913.50], EntityPainting['Cuadro'/6538, l='MpServer', x=-230.00, y=64.00, z=1020.97], EntityItem['item.item.sulphur'/6798, l='MpServer', x=-145.63, y=70.00, z=1064.17], EntityPufferFish['Pufferfish'/399, l='MpServer', x=-113.85, y=48.79, z=934.15], EntityFish['Blue Fish'/400, l='MpServer', x=-117.85, y=49.00, z=941.85], EntityBrownRat['Brown Rat'/401, l='MpServer', x=-107.50, y=74.50, z=952.60], EntityCustomNpc['Guardia'/402, l='MpServer', x=-97.47, y=69.00, z=948.51], EntityPainting['Cuadro'/6527, l='MpServer', x=-244.00, y=64.00, z=1011.03], EntityPainting['Cuadro'/6538, l='MpServer', x=-230.00, y=64.00, z=1020.97], EntityBat['Murciélago'/3493, l='MpServer', x=-69.45, y=40.10, z=1039.17], EntityOctopus['Octopus'/6582, l='MpServer', x=-177.67, y=56.00, z=872.48], EntityFireDragon['Fire Dragon'/183, l='MpServer', x=-209.01, y=72.00, z=902.93], EntityOctopus['Octopus'/6583, l='MpServer', x=-188.44, y=51.00, z=867.96], EntityBlackSpiderMonkey['Black Spider Monkey'/6587, l='MpServer', x=-26.60, y=64.00, z=1138.79], EntityPlayerMob['carnalizer'/5820, l='MpServer', x=-198.50, y=21.00, z=1058.50], EntityZombie['Zombi'/5823, l='MpServer', x=-198.50, y=43.00, z=961.50], EntityItem['item.item.arrow'/3520, l='MpServer', x=-164.78, y=77.00, z=1006.81], EntityCustomNpc['Guardia'/448, l='MpServer', x=-97.47, y=89.00, z=994.45], EntityItem['item.item.bone'/3521, l='MpServer', x=-165.10, y=77.00, z=1006.88], EntityZombie['Zombi'/6344, l='MpServer', x=-71.50, y=52.00, z=1073.50], EntityRat['Rat'/6858, l='MpServer', x=-207.50, y=67.00, z=982.50], EntityItem['item.item.sulphur'/5067, l='MpServer', x=-147.74, y=71.00, z=1042.51], EntityRat['Rat'/6859, l='MpServer', x=-205.50, y=67.00, z=980.50], EntitySockeyeSalmon['Sockeye Salmon'/3798, l='MpServer', x=-192.57, y=62.20, z=885.57], EntityFireDragon['Fire Dragon'/471, l='MpServer', x=-71.79, y=11.00, z=936.18], EntityWildDog['Wild Dog'/5854, l='MpServer', x=-59.50, y=13.00, z=945.50], EntitySkeleton['Esqueleto'/6112, l='MpServer', x=-69.75, y=46.00, z=1049.49], EntityCreeper['Creeper'/2529, l='MpServer', x=-144.50, y=16.00, z=1026.50], EntityBat['Murciélago'/5348, l='MpServer', x=-89.19, y=23.10, z=1039.25], EntityZombie['Zombi'/6120, l='MpServer', x=-84.50, y=23.00, z=1003.50], EntityZombie['Zombi'/6635, l='MpServer', x=-63.50, y=97.00, z=1058.50], EntitySkeleton['Esqueleto'/6383, l='MpServer', x=-101.51, y=15.00, z=1078.83], EntitySkeleton['Esqueleto'/6384, l='MpServer', x=-99.75, y=17.00, z=1069.47], EntitySkeleton['Esqueleto'/6385, l='MpServer', x=-105.23, y=16.00, z=1074.45], EntitySkeleton['Esqueleto'/6386, l='MpServer', x=-101.50, y=15.00, z=1078.10], EntityZombie['Zombi'/6647, l='MpServer', x=-196.50, y=50.00, z=997.50], EntityCreeper['Creeper'/3066, l='MpServer', x=-92.50, y=53.00, z=1026.50], EntityBlackSpiderMonkey['Black Spider Monkey'/506, l='MpServer', x=-43.70, y=88.00, z=1092.22], EntityBlackSpiderMonkey['Black Spider Monkey'/511, l='MpServer', x=-73.40, y=80.00, z=1098.40]]
	Retry entities: 1 total; [EntityLatchedRenderer['Entidad desconocida'/1, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:49)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2292642760 bytes (2186 MB) / 4496293888 bytes (4288 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: ~~ERROR~~ NoClassDefFoundError: net/minecraftforge/common/util/TextTable$1
	Loaded coremods (and transformers): 
WolfArmorCore (WolfArmorAndStorage-1.12.2-3.8.0-universal-signed.jar)
  
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
McLib core mod (mclib-2.4.2-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
FutureMC (future-mc-0.2.11.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.8.jar)
  
CustomSkinLoader (CustomSkinLoader_ForgeLegacy-14.19.1.jar)
  customskinloader.forge.loader.LaunchWrapper
LittlePatchingLoader (LittleTiles_v1.5.85_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Soartex_Fanver.zip
	Current Language: Español (Argentina)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 536.99
	OpenGlRenderer: NVIDIA GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by CreativeMD** [comment]
Looks like an issue of Cooking for Blockheads. You should rather report it to them.

**Comment by SrRapero720** [comment]
Oh lord is not a Cooking for blockheads, is an issue of watermedia. i have no idea why makes classes load in other classloaders and i can't debug nothing atm

**Comment by SrRapero720** [comment]
the curious part is a bug than only happens on  1.12.2 only

**Comment by ZeTaX2002** [comment]
I installed the same exact modpack and everything looks fine. I don't know if it's a client side bug bc it crashes only when joining servers

**Comment by SrRapero720** [comment]
thank god i confirm is not a watermedia bug

**Comment by SrRapero720** [comment]
i re-read your crash and it occurs on client-side related to rendering. if crash only occurs on client when joining server then is client concerning

**Comment by SrRapero720** [comment]
@ZeTaX2002 can you check if this version still causes the crash?
https://github.com/SrRapero720/watermedia/releases/tag/2.0.27-pre1
