### ISSUE TITLE
Crashes upon opening the inventory

### ISSUE THREAD

**Issue by brambora69123** [CreativeMD/LittleFrames#73]
My minecraft crashes when I open the inventory.

MC Version: 1.20.1
Forge version: 47.2.20

Crash report: https://pastebin.com/XuKMYqKP

**Comment by CreativeMD** [comment]
This crash does not make much sense. It seems like the creative picture frame is disabled somehow. Is LittleFrames installed on server side?

**Comment by CreativeMD** [comment]
I will close this issue for now due to inactivity. If this issue persists reply here.
