### ISSUE TITLE
putting an image will make my world crash

### ISSUE THREAD

**Issue by Smirkish** [CreativeMD/LittleFrames#77]
I'am using "LittleFrames_WATERMEDIA_by_Blake_v1.1.4_mc1.12.2" and "watermedia-2.0.28", I have visited one of my maps which is using the previous version of little frames, when I removed the pictures and readded new frames, it just crashed for no reason, I have tried to enter my world again but it crashed.

is there a way to fix this problem? thanks.

**Comment by SrRapero720** [comment]
Is an issue caused by watermedia
https://github.com/SrRapero720/watermedia/issues/42

I am right now investigating what causes it to solve it asap, but at the moment use the private LF build on discord

**Comment by Smirkish** [comment]
in which channel I find the private LF build?

**Comment by Smirkish** [comment]
the releases channel?

**Comment by CreativeMD** [comment]
It's available on curseforge now.
