### ISSUE TITLE
Lag spike with some gifs

### ISSUE THREAD

**Issue by Vodulm** [CreativeMD/LittleFrames#8]
...when placing frame with it (or entering path to clean frame), or when loading chunk with the frame.

https://vimeo.com/506917600

the gifs which causing lag:
![Lorenz system -](https://user-images.githubusercontent.com/73194834/106411550-38512200-644e-11eb-898f-26aa2251d5f5.gif)
![Fillet-2](https://user-images.githubusercontent.com/73194834/106411555-3b4c1280-644e-11eb-9d24-b4d757f6aed3.gif)

**Comment by CreativeMD** [comment]
Enhanced in the newest version. Thanks for letting me know and providing some proper examples for testing (it's not perfect now, but a lot better than before).
