### ISSUE TITLE
Ticking block entity crash when entering URL and saving.

### ISSUE THREAD

**Issue by Coolguy51839** [CreativeMD/LittleFrames#80]
In my own private modpack, opening a picture frame would crash the game prior to the April 23rd update. Post update, you can enter the GUI, but upon saving a URL, the block will tick and the game will crash. I am unaware of any incompatibility - if any - this mod may have with any mod I have installed. Log is attached.

[crash-2024-04-24_02.31.11-client.txt](https://github.com/CreativeMD/LittleFrames/files/15090486/crash-2024-04-24_02.31.11-client.txt)

**Comment by SrRapero720** [comment]
issue is WM in the 2.0.40 removes deprecated methods from `WaterMediaAPI` to backport the new mod bootstrap

LT only need to replace it to non-deprecated methods in the current versiona and will be enough

**Comment by CreativeMD** [comment]
@SrRapero720 how do I update my workspace to the new version? 2.0.40 cannot be found.

**Comment by SrRapero720** [comment]
try again, i forgot to push the 2.0.40 tag 💀

**Comment by SrRapero720** [comment]
anyway, the changes you need to do are in the old versions which contains the deprecated methods and the "use instead" text

**Comment by SrRapero720** [comment]
quick example:
![image](https://github.com/CreativeMD/LittleFrames/assets/29090346/317d5bc9-8704-4a6a-bcd7-cce2d46f8f39)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Would be good if deprecated methods are removed the version jumps up one in the middle to something like 2.1.0, otherwise it is not visible that there could be a breaking change between a version jump.
