### ISSUE TITLE
[Request] Update the 1.19.2 version for newer watermedia version

### ISSUE THREAD

**Issue by QianFuv** [CreativeMD/LittleFrames#81]
This might seem like a waste of time for you... but if you're willing, I believe players on 1.19.2 would greatly appreciate it! The new features and functionalities of LittleFrame and watermedia in the latest version bring a wealth of enhancements, and we hope to port these changes to 1.19.2.🥰🥰🥰

**Comment by SrRapero720** [comment]
right now i am backporting creativecore 1.20.1 to the 1.19.2. depends on CreativeMD if wants to backport the other mods or just do a compatibilty update. (And also that needs some discussion of how to proceed)

**Comment by QianFuv** [comment]
Waiting with hope!(๑>؂<๑）

**Comment by CreativeMD** [comment]
I'm quite sorry, but at the moment I do not have the time. I'm still trying to catch up and fix all the issues. The mod is open source, maybe somebody else can port it.
