### ISSUE TITLE
Add the possibility to change local volume or mute the mod

### ISSUE THREAD

**Issue by guskikalola** [CreativeMD/LittleFrames#84]
Currently the frame's volume is networked, meaning that the volume is the same for everyone. This leads to some users complaning that its too loud for them.

Is it possible to add a local volume option or choice to mute every video?

**Comment by CreativeMD** [comment]
Unfortunately this is an issue of VLC and not LittleFrames directly. Certain settings make it work, but it somehow does not work for everyone. Sorry, but there is little I can do about this issue as it is out of my control.
