### ISSUE TITLE
Problem setting images

### ISSUE THREAD

**Issue by bielmm05** [CreativeMD/LittleFrames#85]
When I pun a picture a link for imgur an de creative frame don't show the picture, it shows a white wall
![imagen_2024-06-06_150639610](https://github.com/CreativeMD/LittleFrames/assets/171942541/19ff5023-90ff-4eb6-853d-e19a06306fd1)
![imagen_2024-06-06_151256036](https://github.com/CreativeMD/LittleFrames/assets/171942541/122497a9-7de4-4cae-bd85-94f295dbf0ce)

**Comment by CreativeMD** [comment]
Sorry for responding so late. Does the issue still persists? If yes what version of minecraft, littleframes and watermedia are you using?

**Comment by Lord-Memester** [comment]
ive had this issue a few times and the fix for me was pressing the reload or play button

**Comment by CreativeMD** [comment]
Interersting. Maybe there is something to report to watermedia as LittleFrames itself does not handle the loading anymore. I will close this issue for now. If there are more information feel free to provide them here. Best is to provide the urls as well to make it easier to test.

**Comment by SrRapero720** [comment]
That is 1.12.2, nothing that watermedia can fix

**Comment by SrRapero720** [comment]
Blake had to add the type on the url request as `image/*`. WaterMedia already do that, 1.12.2 is not longer using WaterMedia
