### ISSUE TITLE
Crash in version 1.21 when trying to look for the Little Picture item

### ISSUE THREAD

**Issue by pedrorfdez** [CreativeMD/LittleFrames#88]
I can access minecraft and create the world flawlessly, but once I try to look for the picture frame item, it crashes.

Specs:
Neoforge 1.21 - 21.0.167
Only used mods: LittleFrames - 1.3.9, CreativeCore - 2.12.6, Watermedia - 2.0.69
Java version: 21.0.4

Crash message: The game crashed whilst rendering entity in world
Error: java.lang.ArrayIndexOutOfBoundsException: Index 128 out of bounds for length 32

Crash report: https://pastebin.com/UFf5LWFu

**Comment by CreativeMD** [comment]
Update CreativeCore. This should fix your issue.
