### ISSUE TITLE
Crash when trying to open the menu

### ISSUE THREAD

**Issue by tanoluciano** [CreativeMD/LittleFrames#93]
when right clicking the frame it just crashes
![imagen_2024-12-16_013641241](https://github.com/user-attachments/assets/0d353187-0734-4d61-9ff9-36bcacbd7e7e)

[debug.log](https://github.com/user-attachments/files/18144834/debug.log)
[latest.log](https://github.com/user-attachments/files/18144836/latest.log)

pwease help, i have both dependencies downloaded

**Comment by tanoluciano** [comment]
by the way im on version 1.20.1

**Comment by CreativeMD** [comment]
Fixed in the newest version. Sorry for the trouble.

**Comment by tanoluciano** [comment]
Thankz
